### PR TITLE
Human 1.18

### PR DESCRIPTION
**Pull request by haowang-bioinfo**
### Main improvements in this PR:
- Fixes (PR #740)
  - remove ACAD10 from the GPRs of MAR03212 and MAR03163, as well as from Human-GEM altogether, as explained in #739
- Fixes (PR #725)
  - remove duplicate 2-oxoadipate dehydrogenase reaction MAR04239, modify GPRs of MAR04599, MAR04209, and MAR06413, remove ENSG00000197444 (OGDHL) gene, as well as incoporate other miscellaneous curations, based on investigation results presented in #719
- Fixes (PR #724)
  - replace inaccurate GPR and reference for MAR04665 with ENSG00000182199 (SHMT2) and "PMID:11087421", as discussed in #720
- Fixes (PR #723)
  - revise mitochondrial Glutathione transport reactions as discussed in #722, by modifying MAR08771, and removing MAR04940 and MAR06391
- Style (PR #721)
  - add Christoff1993 as a contributor
- Fixes (PR #717)
  - resolve duplicate chemical speices hexanoate/hexanoic acid by systematically replacing hexanoate (MAM03684c) with hexanoic acid (MAM02120c), as reported by #716
- Fixes (PR #715)
  - curate GPRs and reaction names of 62 cytosolic short- and medium-chain fatty acid hydrolysis reactions, as proposed in #689
  - add 4 new hydrolysis reactions
  - add 2 new genes THEM4 (ENSG00000159445) and THEM5 (ENSG00000196407)
- Fixes (PR #714)
  - refine GPRs involving LIPT1 (ENSG00000144182) gene, as explained in #683
    - remove LIPT1 (ENSG00000144182) from the GPRs of MAR01088 and MAR01091
    - remove MAR06398, MAR06399, and MAM02398c (lipoyl-AMP), MAR06408, and MAM01701c
    - replace MAM02393m with MAM00209c in MAR08433, MAM01701m with MAM00208c in MAR08434
    - remove MAM02039c and MAM02039e from MAR11346
    - remove MAM02039i and MAM02039m from MAR11361
    - make MAR11361 reversible
- Fixes (PR #713)
  - split formuate dihydroorotate dehydrogenase reaction MAR04575 into two steps by adding new met MAM20019c (FMNH2) and new rxn MAR20167, as advised in #609
- Fixes (PR #712)
  - update and maintain consistency in the met IDs for FMN and FMNH2 and update their annotations, according to #711
- Fixes (PR #710)
  - remove duplicate glycerol-3-phosphate dehydrogenase rxns MAR00478 and MAR00482 and update annotations, as proposed in #599
- Fixes (PR #709)
  - reorganize nucleotide transport reactions [c]<->[m] by adding genes, reactions, updating GPRs, and removing reactions lack of proper transporters, as listed in #694
- Fixes (PR #708)
  - revises tryptophan metabolism reactions and GPRs, as outlined in #545
    - remove ENSG00000159423 (ALDH4A1) from MAR00051
    - remove MAR08564+MAR08565 that are duplicate to MAR04222
    - merge annotations for MAR08564+MAR08565 to that of MAR04222
    - remove derived orhpan met MAM00926c (4-(2-aminophenyl)-2,4-dioxobutanoate)
- Fixes (PR #707)
  - remove MAR06400 and MAR06401 for being duplicate to MAR06403 and MAR06402, respectively, as illustrated in #682
  - update reaction annotation and remove derived orphan met MAM02397c (lipoyl-[ACP])
- Fixes (PR #706)
  - remove lipoic acid transport reactions MAR01483 and MAR06406 that are less accurate duplicates of MAR09608, as notified in #679
  - merge annotations of MAR01483 and MAR06406 into MAR09608, update Rhea ids and references
- Fixes (PR #703)
  - merge "Heme biosynthesis" subsystem into "Porphyrin metabolism", to address issues raised in #356 and #681
- Fixes (PR #702)
  - remove MAR03940 for being redundant with MAR08539+MAR08538, as discovered in #632
- Fixes (PR #701)
  - extensively revise cofactor transport reactions between cytosol <-> peroxisome, as proposed in #640
- Fixes (PR #697)
  - comment-out tasks (37, 38, and 181) with NA[c] metabolite in Cellfile metabolic tasks, as discussed in #696
- Fixes (PR #696)
  - update metabolite name from GAP[c] to D-glyceraldehyde 3-phosphate[c] in Cellfile metabolic tasks, by following the change in #500
- Fixes (PR #582)
  - enable GitHub action check for detecting duplicate reactions by enabling `sanityCheck` to report reactions with identical metabolite IDs
  - remove MAR20012 and MAR20089 that are duplicate to MAR06646 and MAR04545, respectively
- Fixes (PR #512)
  - change the dependency of Yamllint workflow to the repo hosted by `metabolicatlas`

### CODE REVIEW

**Review by Devlin-Moyer — APPROVED** [review]

**Review by mihai-sysbio — APPROVED** [review]
Looks good! I've noticed there two commented-out metabolic tasks. I'm not really fond of having them in that state - I would propose that they are outright removed, or whatever underlying issue there is to be reported and ultimately resolved.

**Comment by haowang-bioinfo** [comment]
> I was playing around yesterday with two different solvers on a knockout panel and I got different results, so I am wondering if the same solver has been used in all the evaluations since v1.12.

good question - for the listed analysis the same solver (gurobi 10) were used except for v1.16

**Comment by haowang-bioinfo** [comment]
the PR message was just updated with #740 after its merging into v1.18, which should be enough and probably just move to a new release

**Comment by JonathanRob** [comment]
> Looks good! I've noticed there two commented-out metabolic tasks. I'm not really fond of having them in that state - I would propose that they are outright removed, or whatever underlying issue there is to be reported and ultimately resolved.

@mihai-sysbio, where are the tasks commented out?

**Comment by haowang-bioinfo** [comment]
>> @mihai-sysbio, where are the tasks commented out?
>
> It's the [Cellfie tasks here](https://github.com/SysBioChalmers/Human-GEM/commits/852a3664463cdd18ff37db9ee666fe9674f88fcc/data/metabolicTasks/metabolicTasks_CellfieConsensus.txt), specifically the last two commits. It makes sense for them to be commented out, but I still think it would be good to have an issue to at some point resolve this.

This most likely refers to the changes made in #697, it was actually discussed but in an atypical way, not via an issue but under a PR (#696)

**Pull request merged**
