### PR TITLE
feat: add gene symbols to model

### PR DESCRIPTION
**Pull request by haowang-bioinfo**
#### Main improvements in this PR:
This PR improves usability by adding gene symbols, as discussed in #539 
- extract gene symbols from `genes.tsv` and embed into Human-GEM as `geneShortNames` field
- enable `importYaml` to load model with this field

**I hereby confirm that I have:**
- [x] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [ ] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
I'm wondering if this will be in line with the cobrapy yaml, and if this format will still make it in the sbml export.

**Comment by haowang-bioinfo** [comment]
have the same concerns that should be ensured

**Comment by haowang-bioinfo** [comment]
the Yaml file with embedded gene names has been tested and now compatible with:
- Human-GEM code set
- Cobra Toolbox
- RAVEN Toolbox
- Cobrapy

**Review by feiranl — APPROVED** [review]
LGTM!

**Comment by haowang-bioinfo** [comment]
to ensure new contributors added to `main` branch will be retained for new release when merging develop branch (that will overwrite main forcefully), those commits were cherry picked to here.

**Pull request merged**
