### PR TITLE
GPR curation for Alanine, Aspartate and Glutamate subsystem

### PR DESCRIPTION
**Pull request by feiranl**
#### Main improvements in this PR:
Fix issues in #548 
* remove gene [ENSG00000134864](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000134864) from the rxn  MAR06972 and MAR06971
* add new rxn [Rhea:16961](https://www.uniprot.org/uniprotkb/Q9BVM4/entry) for gene [ENSG00000134864](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000134864)
* remove [ENSG00000147471](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000147471) from rxn MAR07642
* remove rxn MAR03831 and its corresponding gene [ENSG00000091483](https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000091483)

**I hereby confirm that I have:**

- [x] Tested my code on my own computer for running the model
- [x] Selected `develop` as a target branch
- [x] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by haowang-bioinfo** [comment]
good job!

The new MAR20072 resides in nucleus, which is annotated in [cytosol beside extracellular space](https://www.uniprot.org/uniprotkb/Q9BVM4/entry#subcellular_location) though.

**Comment by feiranl** [comment]
I can remove the nucleus reaction, I added that from the comp annotation in `genes.tsv`.

**Comment by haowang-bioinfo** [comment]
> I can remove the nucleus reaction, I added that from the comp annotation in genes.tsv.

yes, DeepLoc2 does give nucleus prediction that is not supported by Uniprot annotation.

**Comment by feiranl** [comment]
Let's keep it for now as the annotation is in genes.tsv. But we can decide to remove that later?

**Review by haowang-bioinfo — APPROVED** [review]

**Pull request merged**
