### PR TITLE
feat-add new rxn annotations for histidine metabolism

### PR DESCRIPTION
**Pull request by feiranl**
#### Main improvements in this PR:
Fix issues in #553 

Added **39** new rxns according to the new annotations.

**I hereby confirm that I have:**
- [x] Tested my code on my own computer for running the model
- [x] Selected `develop` as a target branch
- [x] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by haowang-bioinfo** [comment]
should the duplicated rxn checking (#390) be detected with this PR?

**Comment by haowang-bioinfo** [comment]
> the duplicate check function will come in next PR.

very good

> I performed a manual check for this PR

what's the checking results?

**Comment by feiranl** [comment]
According to the check, this PR doesnot introduce new duplicate rxns

**Review by haowang-bioinfo — APPROVED** [review]
looks good

**Pull request merged**
