### PR TITLE
Fix-Phe, Tyr and Trp biosynthesis and Porphyrin metabolism

### PR DESCRIPTION
**Pull request by JHL-452b**
#### Main improvements in this PR:

As proposed in #855 
- Remove `ENSG00000184254` from MAR06749;
- Remove `ENSG00000184254` from MAR06754;
- Remove `ENSG00000184254` from MAR06761;
- Remove `ENSG00000184254` from MAR06767;
- Remove `ENSG00000184254` from MAR06791;
- Remove `ENSG00000130508`, `ENSG00000117592` from MAR06808;
- Remove `ENSG00000117592` from MAR06813;
- Remove `ENSG00000166507`, `ENSG00000140835`, `ENSG00000138653`, `ENSG00000136720`, `ENSG00000124302`, `ENSG00000183196`, `ENSG00000135702`, `ENSG00000171004`, `ENSG00000175040`, `ENSG00000175229` from MAR06829;
- Remove `ENSG00000167419`, `ENSG00000117592`, `ENSG00000130508` from MAR07628;
- Remove `ENSG00000184254` from MAR06748;
- Remove `ENSG00000196616` from MAR06756;
- Remove `ENSG00000184254` from MAR06760;
- Remove `ENSG00000151093` from MAR02781.

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [ ] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by JHL-452b** [comment]
Aha, it looks like the updated MACAW output is showing garbled text.🤔

**Comment by edkerk** [comment]
Should be resolved now, let's see what will be posted.

**Comment by JHL-452b** [comment]
Hooray, all the checks passed!

However, there is a small problem. If two or more PRs are submitted at the same time, will the server used for the checks crash? After all, each round check takes a long time, and the submission of multiple PRs may be unavoidable.

**Comment by edkerk** [comment]
The server doesn't crash, as the runs are queued. I think there might be something with submitting the results back, but if this appears I can manually restart the runs.

**Review by feiranl — APPROVED** [review]
LGTM! Please resolve the conflicts and merge this PR!

**Pull request merged**
