### PR TITLE
Fix/hexanoate

### PR DESCRIPTION
**Pull request by pranasag**
#### Main improvements in this PR:
This PR addresses #716 by removing the hexanoate [MAM03684c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03684c) species, and swapping hexanoic acid [MAM02120c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02120c) where applicable.

Changes done:
- Added mitochondrial and peroxisomal versions of [MAM02120c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02120c), MAM02120m and MAM02120x, respectively
- Species [MAM03684c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03684c), [MAM03684m](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03684m), [MAM03684x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03684x), and [MAM03684e](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03684e) have been removed
- Removed reactions of hexanoate activation ([MAR09949](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR09949)), transport ([MAR11292](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR11292)) and exchange ([MAR11293](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR11293)), which are duplicate to [MAR11544](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR11544), [MAR00167](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00167), and [MAR09811](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR09811), respectively
- In reactions [MAR10374](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10374), [MAR10377](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10377), [MAR11290](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR11290), [MAR11291](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR11291), [MAR20040](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR20040), hexanoate was changed to hexanoic acid
- Set reaction [MAR10377](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10377) irreversible, as explained in #689
- updated GPRs of MAR10377 and MAR10374 with ENSG00000101473 and ENSG00000123130, respectively

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by haowang-bioinfo** [comment]
looks nice - please also merge annotation MAM03684 into MAM02120, such as the BiGG id

**Comment by pranasag** [comment]
Good spot - added the BiGG id to MAM02120. This was the only annotation missing (MAM02120 was way more complete than MAM03684.

**Review by haowang-bioinfo — APPROVED** [review]
good work

**Comment by haowang-bioinfo** [comment]
if there is any evidence supporting an irreversible [MAR10377](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10377)?

**Comment by pranasag** [comment]
It involves hydrolyzing a high-energy bond, so the short answer is "thermodynamics". This traces back to the issues reported by Devlin Moyer and me (#527, #689), where [rightfully] setting reactions irreversible required additional fixes elsewhere

**Comment by haowang-bioinfo** [comment]
thanks for the clarification - may the GPR be updated with any ACOTs (#689)?

**Comment by pranasag** [comment]
For the peroxisomal reaction [MAR10377](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10377), the best candidate is ACOT8 (ENSG00000101473), as ACOT4 and ACOT6 are known to be rather specific to certain acyl-CoAs. Alongside, mitochondrial reaction [MAR10374](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR10374) was also missing a GPR, I suggest ACOT9 (ENSG00000123130) since mitochondrial ACOTs with known specificity (ACOT2, ACOT7, and THEM5) are specific to very long-chain FAs.

**Comment by haowang-bioinfo** [comment]
makes sense - please go ahead to implementation

**Pull request merged**
