### PR TITLE
feat: add reaction names from KEGG

### LINKED ISSUE #181: missing reaction names
### Description of the issue:
A large amount of reactions in the model do not have a descriptive name.

#### Expected feature/value/output:
More reactions with descriptive names in the model.

#### Current feature/value/output:
8200+/13400+ reactions without name.

#### Reproducing these results:
search for  `    - name: ""\n      - metabolites` in the .yml

Most of the current reaction names in the model are identical to the BiGG or Recon3D annotation. But using the BiGG / Recon3D, KEGG and Reactome external identifiers I estimate that 3500+ additional reaction names could be imported in the model (based on v1.3). 

I think names then could also be curated or auto-generated by considering the equation and/or EC code of enzymes associated to the reactions.

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:
This PR resolves #181 by taking 2000 reaction names from KEGG (the first supplied). The work was done fully scripted on [Google Colab](https://colab.research.google.com/drive/17X0Qx0H4pwjZjLLWHnpp5ac2daH9hOxs?usp=sharing) and also moved to the `/code` folder.

**I hereby confirm that I have:**

- [ ] Tested my code on my own computer for running the model
- [x] Selected `develop` as a target branch

### CODE REVIEW

**Comment by JonathanRob** [comment]
> it seems that only 2 of these reactions had names before

I compared the `rxnNames` fields for the model on `develop` and on this branch, and found more than 2 reactions whose names had been overwritten, where one case was a deletion of the name.

rxn | rxnName (original) | rxnName (new)
-- | -- | --
MAR04606 | Formation of homocarnosine | L-histidine:4-aminobutanoate ligase (ADP-forming)
MAR04607 | Hydrolysis of homocarnosine | alpha-Aminobutyryl histidine hydrolase
MAR05387 | Acireductone Synthase | 5-(methylthio)-2,3-dioxopentyl-phosphate phosphohydrolase (isomerizing)
MAR05389 | Acireductone Dixoygenase 1 | 1,2-dihydroxy-5-(methylthio)pent-1-en-3-one:oxygen oxidoreductase   (formate-forming)
MAR01940 | Formation of 21-hydroxypregnenolone | pregnenolone,NADPH-hemoprotein reductase:oxygen oxidoreductase   (21-hydroxylating)
MAR01941 | Formation of 11-deoxycorticosterone | 21-Hydroxypregnenolone:NAD+ 3-oxidoreductase
MAR02041 | 17-beta-estradiol 17-dehydrogenase | Estradiol-17beta:NADP+ 17-oxidoreductase
MAR01317 | NAD Dependent 11-Hydroxythromboxane   B2 Dehydrogenase
MAR09798 | Formation of Alanylalanine | D-alanine:D-alanine ligase (ADP-forming)
MAR01044 | Ferrochelatase, Mitochondrial | protoheme ferro-lyase (protoporphyrin-forming)

It would be good to double check these to ensure they make sense, as well as spot-check several other reactions with new name assignments to confirm they're OK.

**Comment by mihai-sysbio** [comment]
Interesting you found more conflicts @JonathanRob, I'm not sure how I misseed them.

This conflict between curated data and database-fetched data is a recurring problem. My stance here is to not keep track of manual curations done on top of database-fetched data, so I'm going to propose a different approach.

Instead of _overwriting_ reaction names, I can edit the script to only fill in reaction names where none existed, and push a new commit. With this approach we avoid the need to double-check the conflicts; only the spot-checking would need to be done.

**Comment by haowang-bioinfo** [comment]
> Instead of overwriting reaction names, I can edit the script to only fill in reaction names where none existed, and push a new commit. With this approach we avoid the need to double-check the conflicts; only the spot-checking would need to be done.

this seems a decent solution, would be good to upload the code as well

**Comment by mihai-sysbio** [comment]
The force-pushed commit [c5ec9fe](https://github.com/SysBioChalmers/Human-GEM/pull/367/commits/c5ec9fe55e7c7c31a4edba3b077ea531eef85cf3) overwrites the previous work. Now, only empty reaction names are filled in. The Python script is also attached. Given the changes, I'm re-requesting reviews.

**Comment by haowang-bioinfo** [comment]
@mihai-sysbio thanks for providing the script, whose output `curated-Human-GEM.yml` has exactly the same content as ` Human-GEM.yml` after running. 

However, the code still reports `Modified reactions: 385`. Not sure the reason but there should be no more modifications. Could you please check this out and maybe add more comments to the code for easier understanding and reviewing.

**Comment by mihai-sysbio** [comment]
The modified reaction increment is counting the attempts where a reaction with no name (`""`) is replaced with the name for the associated KEGG id from `reactions.tsv`. `385` indicates there are still quite a few cases with reactions that don't have a name even in KEGG. I guess I could change the output so as to more clearly indicate this, but as you note @haowang-bioinfo  this wouldn't have any practical implications, since:

>  output `curated-Human-GEM.yml` has exactly the same content as ` Human-GEM.yml` after running

My approach has been that of a one-time curation, so I am in favor of not over-engineering the script. If we are aiming for turning this into a scripted, recurring curation, I would prefer to have a different issue, since the parsing of the `yml` is a bit clunky anyway.

**Comment by haowang-bioinfo** [comment]
> 385 indicates there are still quite a few cases with reactions that don't have a name even in KEGG. I guess I could change the output so as to more clearly indicate this

That would be good. Agree to not over-engineering

**Comment by mihai-sysbio** [comment]
> That would be good. Agree to not over-engineering

@haowang-bioinfo I've updated the script that now outputs (on the second run):

> Reaction names adopted from KEGG: 0
Blank names also blank in KEGG: 385

The latest commit bd111e8 is force-pushed because it's now rebased on  `develop`, making for an easy merge without needing to resolve conflicts.

**Review by haowang-bioinfo — APPROVED** [review]
> I've updated the script that now outputs (on the second run)

thanks

**Pull request merged**
