### PR TITLE
adding CHEBI ids to some MAMids

### PR DESCRIPTION
**Pull request by ANiknejad**
fix: adding some CHEBI xref to the metabolites.tsv file, by filling up the column 'metChEBIID' (work in progress)

**I hereby confirm that I have:**

- [X] Selected `develop` as a target branch

### CODE REVIEW

**Comment by JonathanRob** [comment]
Looks great, thank you for this, @ANiknejad!

**Review by JonathanRob — APPROVED** [review]

**Comment by Hao-Chalmers** [comment]
@ANiknejad fantastic. May I know how much work do you plan to include in this PR i.e. roughly how many more will be added?

**Comment by mihai-sysbio** [comment]
I guess the question is about knowing if it makes sense to keep the pull request open longer, so that more commits can easily be added to the same branch? The other option would be to merge this in and open a new pull request for the new work.

**Comment by ANiknejad** [comment]
Hello, I guess, it could be a good idea 'to merge this in and open a new pull request for the new work.' I will anyway take some vacation starting from tomorrow Tuesday 21th, and back on 5th January. I wish you all a great holiday Season.

**Review by Hao-Chalmers — APPROVED** [review]
fantastic work @ANiknejad

**Pull request merged**
