### PR TITLE
Human 1.5

### PR DESCRIPTION
**Pull request by Hao-Chalmers**
### Main improvements in this PR:
- Fixes (PR #206):
	- curate subSystems names as proposed in #205
		- replace **131** `Metabolism of xenobiotics by cytochrome P450` with `Xenobiotics metabolism` 
		- change **2** `Alkaloids Biosynthesis` to `Alkaloids biosynthesis`
- Fixes (PR #202):
	- Ensembl id mapping file is updated from version **95** to **101**
	- remove genes `ENSG00000281028` and `ENSG00000285441` because they were reported to be retired in Ensembl (#200)
- Fixes (PR #199):
	- correct gene association with reaction `HMR_8177`, as reported in #198
	- update references and confidence scores for `HMR_8171`, `HMR_8177`, `HMR_8180`, `HMR_8181`, and `HMR_8182`
- Features (PR #195):
	- add new functions `getModelFromOrthology`, `extractAllianceGenomeOrthologs`, and `replaceGrRules`, for expanding the applications of `Human-GEM`

### CODE REVIEW

**Review by mihai-sysbio — APPROVED** [review]
Everything looks good to me.
One minor comment is the target version in the PR name. According to semantic versioning (Major.Minor.Patch), I'm inclined to see this as a `1.5`.

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio sounds a very good idea to turn this a minor release.

**Comment by Hao-Chalmers** [comment]
@JonathanRob what do think about having this as v1.5?

**Comment by JonathanRob** [comment]
Sounds good to me!

**Review by JonathanRob — APPROVED** [review]

**Pull request merged**
