### PR TITLE
refactor: use Python 3, has latest pip for cobra

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:
This PR migrates Python to version 3, which removes the need to upgrade `pip` before installing `cobra`. It also addresses the `FutureWarning` message which cobrapy outputs.

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
Great improvement @Hao-Chalmers 👍 for the action to pass it needs the model file in the new location, ie #188 should be merged first.

**Comment by JonathanRob** [comment]
Agreed, nice addition, @Hao-Chalmers.

A small question - should this new `basicCheck.py` script be placed in the `.github/workflows/` directory?

**Comment by Hao-Chalmers** [comment]
@JonathanRob not sure about the location. @mihai-sysbio what do you think?

Some thoughts about `basicCheck`: now it has checks for cobrapy import and consistency with annotation files. More tests may be added later either by curator or user, to whom the `code/test` folder probably is better to work with?

**Comment by mihai-sysbio** [comment]
Imho tests should be designed to run on their own, and just called in the workflow, so that users can have the freedom of testing whenever they prefer; I'd leave tests in `code/test`.

**Comment by JonathanRob** [comment]
Ok, sounds good @mihai-sysbio @Hao-Chalmers! No need to move things around then.

**Pull request merged**
