### PR TITLE
Fix Representation of ETF

### PR DESCRIPTION
**Pull request by Devlin-Moyer**
#### Main improvements in this PR:
Implements the (updated) changes proposed in #608:
* Replaces existing GPR of `MAR06911` with `ENSG00000140374 or ENSG00000105379 or ENSG00000171503 or ENSG00000100033 or ENSG00000250799 or ENSG00000115159 or ENSG00000102967 or ENSG00000016391`
* Remove `MAR00562` and `MAR00563` for being redundant with `MAR06911`
* Removes `MAM03573m` and `MAM03574m`

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by Devlin-Moyer** [comment]
Oh whoops the YAML validation probably failed cuz I forgot to also remove the ETF "metabolites" (although the error message it printed was not super easy to interpret)

**Comment by haowang-bioinfo** [comment]
>This change was made in https://github.com/SysBioChalmers/Human-GEM/pull/489, and I missed that because I only checked the Metabolic Atlas website and not the most current YAML file, and apparently the Metabolic Atlas website's version of Human-GEM has not been updated in at least two releases of Human-GEM.

yes, Metabolic Atlas is out of sync recently

**Comment by haowang-bioinfo** [comment]
> So instead of just adding the genes mentioned in https://github.com/SysBioChalmers/Human-GEM/issues/608 to the existing GPR of MAR06911, I replaced the existing one.

please clarify the latest plan, and also update proposed implementations

**Comment by Devlin-Moyer** [comment]
You mean update the proposed changes in #608?

**Comment by haowang-bioinfo** [comment]
yes, #608 and PR message of #612

**Comment by Devlin-Moyer** [comment]
(that last commit was taking care of the merge conflict in the deprecated metabolites and reactions files because this branch did not have the new rows in those files for the malonyl-carnitine reactions and metabolites removed in #605)

**Review by haowang-bioinfo — APPROVED** [review]

**Comment by haowang-bioinfo** [comment]
would you please add [this paper](https://febs.onlinelibrary.wiley.com/doi/full/10.1111/febs.16164) to the reference of `MAR06911`

**Pull request merged**
