### PR TITLE
feat: enforce github actions checkout depth

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:
This PR aims to try different ways of avoiding workflow failures as in https://github.com/SysBioChalmers/Human-GEM/pull/321.

**I hereby confirm that I have:**

- [x] Selected `develop` as a target branch

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
While this should not, in theory, make a difference, I'm wondering if this will resolve the caching issues that I suspect are the source of the failures in the Actions.

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio could the commit in this PR be cherry picked to #321 and see if it makes a difference?

**Comment by mihai-sysbio** [comment]
@Hao-Chalmers triggering this workflow requires a PR, so I ended up mirroring this in #324 .

**Comment by Hao-Chalmers** [comment]
The same error recurred in #324, this probably means that there is a flaw in the `develop`?

**Pull request closed without merging**
