### PR TITLE
fix: remove the extra space at the end of the subsystem and reaction names

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:
There subsystem `Cholesterol biosynthesis 1 (Bloch pathway)` had an extra space at the end, which resulted in an error when deploying on Metabolic Atlas. Seeing no other confli

**I hereby confirm that I have:**

- [ ] Tested my code on my own computer for running the model
- [x] Selected `develop` as a target branch

### CODE REVIEW

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio looks good. Please check all subsystems and remove any leading and trailing spaces in this PR.

**Comment by mihai-sysbio** [comment]
Alright, I removed all cases when there was a space just before the end quotes.

**Comment by Hao-Chalmers** [comment]
Super

**Comment by mihai-sysbio** [comment]
I was going through the changes and noticed the last one`HMR_10046` has an incomplete name.

**Comment by Hao-Chalmers** [comment]
The name of `HMR_10046` should be `1,2-diacylglycerol-LD-PC pool transport(Cytosol to Extracellular)`.

**Review by Hao-Chalmers — APPROVED** [review]

**Pull request merged**
