### PR TITLE
Fix/acot curation

### LINKED ISSUE #689: Short- and medium-chain fatty acids don't have hydrolysis rxns
#### Current behavior:
Hi everyone, 
after the fix #557/discussion in #527, the Human-GEM v1.16 cannot produce free C4-C11 fatty acids (the ATP-generating reaction was the only route to get free FAs from their CoA-bound forms). Acyl-CoA hydrolysis reactions for C12 and longer FAs [exist already](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00189).

#### Expected feature/value/output:
We would need cytosolic reactions for [C4-](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01412c), [C6-](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02122c), [C8-](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02644c), [C10-](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01650c), and [C11-CoA](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM03116c) hydryolysis in the same spirit as for C12 [MAR00189](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00189): `H2O[c] + acyl-CoA[c] => CoA[c] + H+[c] + free fatty acid[c]`.

### PR DESCRIPTION
**Pull request by pranasag**
#### Main improvements in this PR:
This PR improves/fixes #689 by:
- Added acyl-CoA hydrolysis reactions for C4, C8, C10, and C11-CoA, assigned a new GPR for existing C6-CoA hydrolysis reaction [MAR11544](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR11544),
- Added THEM4 (ENSG00000159445) and THEM5 (ENSG00000196407) genes to the model,
- Assigned new GPRs for existing acyl-CoA hydrolases, and added human-readable names to these reactions
- Consistency workflows were throwing errors about orphan genes ENSG00000123130 and ENSG00000196407, these localize to mitochondria, so currently added them to at least one mitochondrial acyl-CoA hydrolase reaction. Seems that this also needs some extra curation in the future (e.g. [MAR02487](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR02487) should be split into `H2O [m] + stearoyl-CoA [m] -> CoA [m] + H+ [m] + stearate [m]` and `ATP [m] + CoA [m] + stearate [m] -> stearoyl-CoA [m] + AMP [m] + PPi [m]`.

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by haowang-bioinfo** [comment]
@pranasag this is great

a minor change would be required to adjust the range of newly added reaction ids from MAR20167-70 to MAR20169-72, according to latest changes in #714.

**Comment by pranasag** [comment]
@haowang-bioinfo I have changed the reaction IDs, but there seem to be some remaining conflicts, could you please check?

**Comment by haowang-bioinfo** [comment]
yes will check

**Comment by haowang-bioinfo** [comment]
conflicts to `develop` branch are resolved

**Comment by pranasag** [comment]
Nice, thank you @haowang-bioinfo!

**Review by Devlin-Moyer — APPROVED** [review]

**Comment by haowang-bioinfo** [comment]
@pranasag can you double check the GPRs of MAR00358 and MAR00362, they were proposed as `ENSG00000184227 or ENSG00000136881 or ENSG00000205669` in # but now are `ENSG00000184227 or ENSG00000097021 or ENSG00000136881`.

**Comment by pranasag** [comment]
@haowang-bioinfo thank you for your sharp eye, indeed these GPRs were incorrect. Not sure why this glitch happened, I have added the GPRs manually from the .csv file I shared in #689.

Also, since we are here, I made a small fix, where MAR10389, which is a transporter reaction, was assigned to the subsystem of exchange reactions (contributed by Christoff Odendaal @Christoff1993).
P.S. The Metabolic Atlas website does not find an entry for MAR10389, thus I couldn't link it to the website.

**Review by haowang-bioinfo — APPROVED** [review]

**Comment by haowang-bioinfo** [comment]
@pranasag @Christoff1993 thank you for the contribution - welcome to continue on fixing mitochondrial acyl-CoA hydrolase reactions

**Comment by haowang-bioinfo** [comment]
@all-contributors please add @Christoff1993 for the bug fixing.

**Pull request merged**
