### PR TITLE
Human 1.10

### PR DESCRIPTION
**Pull request by Hao-Chalmers**
### Main improvements in this PR:
- Fix (PR #324):
	-  force cache refreshing by using commit SHA as key, to address random GH action failures
- Style (PR #320):
	- simplify `contributing guidelines` to adapt with yaml workflow
- Features (PR #315):
	- expand to cover all participants who have constructively contributed to `Human-GEM`, as claimed in #288
- Fixes (PR #313):
	- removed beta-D-glucose detour, based on the discussion in #307
		- MAM01389c, MAR07746, MAR07748, MAR07749 are removed
		- MAR07747 changed stoichiometry from `beta-` form to generic
- Fixes (PR #312):
	- remove KEGG annotation to MAM03165c, as proposed in #310
- Features (PR #305):
	- Include `Cellfie's` metabolic tasks, as discussed in #280
		- all metabolite ids are adjusted for `Human-GEM` except `Try_ggn`
		- change compartment `[x]` into `[s]`
		- metes that are both in `IN` and `OUT` columns (e.g. H20) are removed from `OUT`
- Fixes (PR #302):
	- removed ChEBI annotation `71980` to MAM00535c, as suggested in #273
- Features (PR #298):
	- adopt [`all-contributors`](https://allcontributors.org/) to recognize those who contributed and improve their visibility

### CODE REVIEW

**Comment by Hao-Chalmers** [comment]
Despite of the failure of `YAML validation`, manual check in `develop` branch confirmed that `All checks have passed`.

**Comment by mihai-sysbio** [comment]
> Despite of the failure of `YAML validation`, manual check in `develop` branch confirmed that `All checks have passed`.

@Hao-Chalmers this failure seems to appear quite often nowadays. Should we wait with the merge until a fix is merged into `develop`?

**Comment by Hao-Chalmers** [comment]
I tested YAML conversion and validation manually, both actually passed @mihai-sysbio

**Review by JonathanRob — APPROVED** [review]
I can also confirm that a manual run of the `sanityCheck.py` script (where GH is claiming to fail) ran successfully for me.

**Comment by Hao-Chalmers** [comment]
Both failures occurred at the same place: gene lists in the model and annotation file are mismatch.

**Comment by Hao-Chalmers** [comment]
There are 2 actions setup for checks in Human-GEM, why each was called twice? @mihai-sysbio

**Comment by mihai-sysbio** [comment]
> There are 2 actions setup for checks in Human-GEM, why each was called twice? @mihai-sysbio

I suspect it's because of the duplicated triggers:
```
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]
```

**Comment by mihai-sysbio** [comment]
Commit 339ff64 avoids duplicated workflow runs spotted by @Hao-Chalmers [above](https://github.com/SysBioChalmers/Human-GEM/pull/321#issuecomment-918261454).

**Comment by mihai-sysbio** [comment]
I would recommend merging as is, with the caching fix and the duplicated action fix need to make their way to `main`.

**Pull request merged**
