### PR TITLE
feat: implement MA ids for reactions and metabolites

### PR DESCRIPTION
**Pull request by Hao-Chalmers**
### Main improvements in this PR:
* replace `rxns` and `mets` fields in Human-GEM and annotation `tsv` files with MA ids using script `implementeMAID`, as planned in #265

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- [X] Passed `testYamlConversion` check
- [X] Selected `develop` as a target branch

### CODE REVIEW

**Review by mihai-sysbio — APPROVED** [review]
Looks good! Here are some thoughts, please mark as complete at your discretion:
- [ ] something should be done to the `metsNoComp` column
- [ ] the files where the "old" MA ids will be kept should be added to this PR

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio what do you mean by `the files where the "old" MA ids will be kept`?

**Comment by Hao-Chalmers** [comment]
my thoughts:

1. the "old MA ids" will become the ids once the PR is merged;
2. in my understanding, there is no plan for for lessons 6 and 7. But it's good to have one asap;
3. yes, this PR is to address just #265

**Comment by mihai-sysbio** [comment]
I see as part of #265 also to address lessons 6 and 7, and to solve these there would need to be a place to store the MA ids that get removed from the model ("old", ie used in the past but not used any longer).

**Comment by Hao-Chalmers** [comment]
Agree, would like to see specific plan proposed under #265

**Pull request merged**
