### PR TITLE
feat: change multiple compartment abbreviations

### PR DESCRIPTION
**Pull request by JonathanRob**
### Main improvements in this PR:
This is a more extensive/exhaustive implementation of #330 to address discussions in #314.

Three Human-GEM compartment abbreviations are changed in the model file, metabolite annotation file, metabolic task files, and the `addBoundaryMets` function:

| Compartment | Abbreviation | New Abbreviation
| --- | --- | --- |
| Extracellular | `s` | `e` |
| Boundary | `x` | `b` |
| Peroxisome | `p` | `x` |

Since the changes (diffs) are quite large, I implemented the changes with a script `changeCompAbbrevs` in `code/modelCuration/`.

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch

### CODE REVIEW

**Review by smoretti — APPROVED** [review]
I did not know all your code and files but the ones I know look OK

**Review by mihai-sysbio — APPROVED** [review]
That's neat!
Just so you know, there is a reference to `'x'` in a commented line in `importYaml`, which might be good to either update or delete.

**Comment by JonathanRob** [comment]
> Just so you know, there is a reference to `'x'` in a commented line in `importYaml`, which might be good to either update or delete.

@mihai-sysbio Good catch, I have now removed that line.

**Comment by Hao-Chalmers** [comment]
I've gone through all the changes that look good to me. @JonathanRob nice work.

though there's a little concern about commit 5e6af0f92bde6079cb68efeb6d4616691577dcb8 that marked all these previous metabolite ids as deprecated, this is probably overkill. What we are trying to do here is replacing ids i.e. adapting to the BiGG (or KBase/SEED) scheme (#314), which actually reserved `p` and `s` for compartments `periplasm ` and `eyespot`, respectively. And this commit excluded the possibility of their occurrence in periplasm and/or eyespot (even though HumanGEM doesn't has these compartments that might be added later). So this commit appears to be unnecessary and should be abandoned. What do you guys think?

**Comment by Hao-Chalmers** [comment]
now the changes introduced by #339 led to conflicts in `metabolites.tsv`

**Comment by mihai-sysbio** [comment]
It looks to me like we are following the [BiGG specification here](https://github.com/SysBioChalmers/Human-GEM/issues/314#issuecomment-919774532), but maybe we should reference the source directly.
For [ModelSEED the template for Human on the `master` branch](https://github.com/ModelSEED/ModelSEEDDatabase/blob/194ac8afe48f8a606c0dd07ba3c7af10c02ba2fd/Templates/Human/Compartments.tsv) looks fairly compatible with implemented changes.
| id | name |
| - | - |
| c0 | Cytosol |
| e0 | Extracellular |
| a0 | Carboxysome |
| g0 | Golgi |
| l0 | Lysosome |
| m0 | Mitochondria |
| n0 | Nucleus |
| r0 | Endoplasmic_Reticulum |
| x0 | Peroxisome |

**Comment by mihai-sysbio** [comment]
Just a ping to advance this PR.
@JonathanRob do you think you can resolve the conflicts?
@haowang-bioinfo is it okay that we are waiting for your review?

**Comment by JonathanRob** [comment]
Once #343 is merged, the conflicts should be resolved.

**Comment by mihai-sysbio** [comment]
To avoid future merge conflicts, I think it makes sense to hold off on creating any PRs until the metabolites get renamed. This makes the current PR a priority. @JonathanRob let me know how I can help.

**Comment by JonathanRob** [comment]
@mihai-sysbio yes, exactly. I will merge #343 to see if that solves the conflict on this PR. If that doesn't work, then I may ask for some help.

**Comment by haowang-bioinfo** [comment]
> @haowang-bioinfo is it okay that we are waiting for your review?

@mihai-sysbio sorry I missed this message

**Pull request merged**
