### PR TITLE
fix: annotation for MAM03165c

### PR DESCRIPTION
**Pull request by ANiknejad**
see issue #310

### CODE REVIEW

**Comment by Hao-Chalmers** [comment]
@ANiknejad please modify this PR by changing the target branch from `SysBioChalmers:main` to `SysBioChalmers:develop`

**Comment by JonathanRob** [comment]
The only change here is to the `metabolites.tsv` file, yet the "YAML validation" check is failing... why is that? @mihai-sysbio or @Hao-Chalmers.

**Comment by Hao-Chalmers** [comment]
It's strange that the error message is `Gene annotation mismatch!`, but this PR has nothing to do with genes ...

**Comment by mihai-sysbio** [comment]
Previously, I have encountered cases where aggressive caching led to workflow failures. As expected, running this check locally returns:
```
All checks have passed.
```
After having requested several re-runs of this workflow leading to failures, I would be okay with merging as-is.

**Review by Hao-Chalmers — APPROVED** [review]

**Pull request merged**
