### PR TITLE
feat: yaml worflow

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:
This PR addresses all yaml indentation issues from #169 and adds a GitHub Action to run `yamllint` on PRs to `master` and `devel`, and pushes to `devel`. The `yamllint` configuration `{extends: default, rules: {line-length: disable}}`, which, unlike `extends: relaxed` means most problems will result in errors, [as per the documentation](https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration). The `line-length` is disabled because it's unlikely this will be addressed.
I've ran `testYamlConversion.m` on the new yaml but nothing more.

Edit: Cobrapy import has also been added to the workflow.

**I hereby confirm that I have:**

- [x] Tested my code on my own computer for running the model
- [x] Selected `devel` as a target branch

### CODE REVIEW

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio it's very nice to have GH actions checks!

**Comment by Hao-Chalmers** [comment]
There is still one warning reported from yamllint and maybe worth to fix it here?
`1:1       warning  missing document start "---"  (document-start)`

**Comment by mihai-sysbio** [comment]
I saw that, but was afraid to fix it - I'm not sure if _all_ yaml parsers can handle `---`.

**Comment by JonathanRob** [comment]
It looks like the changes to the yaml indentation (d075b07) broke compatibility with cobrapy, unfortunately.

**Comment by mihai-sysbio** [comment]
Compatibility with `cobrapy` has been restored, and is now also part of the same GH action.

**Comment by mihai-sysbio** [comment]
Thanks @Hao-Chalmers and @JonathanRob for the feedback in resolving the PR.

**Comment by BenjaSanchez** [comment]
@Hao-Chalmers @mihai-sysbio I found this PR and I wonder why are all these modifications to `writeHumanYaml.m` not a part of RAVEN's `writeYaml.m`? Moreover, any reason to have `writeHumanYaml.m` at all and not directly rely on `writeYaml.m`? That way all these changes could benefit all repos that uses `writeYaml.m`, for instance it would resolve failing tests at https://github.com/SysBioChalmers/yeast-GEM/pull/236

**Comment by mihai-sysbio** [comment]
As you're suggesting @BenjaSanchez I also think it's better to fix problems at the source, in this case to apply the fixes directly to RAVEN. However, I'm not sure why [`writeHumanYaml`](https://github.com/SysBioChalmers/Human-GEM/commits/3783401ec8c9b662caf8fad1d22b2c9fa1435b5a/ComplementaryScripts/Functions/writeHumanYaml.m) came to be - maybe @JonathanRob remembers?

**Comment by Hao-Chalmers** [comment]
@BenjaSanchez the development of `writeHumanYaml` was triggered by this issue #71.

**Comment by JonathanRob** [comment]
The initial form of `writeHumanYaml` was super specific to Human-GEM and its parsing by Metabolic Atlas, so at that time it didn't make sense to apply the changes directly to RAVEN. Now that it has developed more, maybe it has reached a point that it is feasible to work toward merging it with the RAVEN function.

**Comment by mihai-sysbio** [comment]
That's my mistake then - pushing for the development of a custom yaml export instead of relying upon the RAVEN export with potential modifications. I fully support the merging of the two.

**Comment by Hao-Chalmers** [comment]
I also support the merging, which does appear to the right time point after evolvements.

**Comment by BenjaSanchez** [comment]
@JonathanRob @mihai-sysbio @Hao-Chalmers sounds great! Anyone from the human-GEM / Metabolic Atlas side that would like to take up this? I'm not familiar with all these additional Metabolic Atlas-specific fields... I can imagine that a `metabolic_atlas` flag that defaults to false would be the most sensible way of doing it? I opened https://github.com/SysBioChalmers/RAVEN/pull/309 that already adds quotes to strings, so work could be continued from there?

**Comment by Hao-Chalmers** [comment]
I can start to work on this, maybe also migrate `readYaml` to RAVEN, in addition to `writeYaml`.

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio I do not view #71 as a mistake, but improvement or enhancement instead.

@BenjaSanchez the first issue about `writeYaml` migration is how to deal with  `metadata` in RAVEN? The metadata info will add two new fields `version` and `description` to model spec and adjust existing `annotation` field.

**Comment by BenjaSanchez** [comment]
@Hao-Chalmers are you referring to the 1st field in the human-GEM yml `metaData`? In practice this should not be a problem for `writeYaml`, as you could choose to write it only if the information is available in the model structure under your current format, and otherwise skip it, keeping compatibility with models that don't have that data.

Having said that, is the standard for `metaData` documented somewhere? Perhaps these missing field should become a part of `RAVEN_structure_fields.csv`? Although I do see a `description` field already matching there, what's the difference between the two?

**Comment by Hao-Chalmers** [comment]
@BenjaSanchez will start a [RAVEN](https://github.com/SysBioChalmers/RAVEN) issue to address this.

**Comment by mihai-sysbio** [comment]
@Hao-Chalmers which issue in RAVEN should I be watching? These are open:
- https://github.com/SysBioChalmers/RAVEN/issues/77
- https://github.com/SysBioChalmers/RAVEN/issues/107
- https://github.com/SysBioChalmers/RAVEN/issues/311

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio both #77 and #107 should be closed, and I did.

There is pending conclusions to #311, which seems to be relevant to `standard-GEM` as well.

**Pull request merged**
