### PR TITLE
Human 1.19

### PR DESCRIPTION
**Pull request by JHL-452b**
#### Main improvements in this PR:

- Features (PR #731)
  - Add SMILES and InChI of metabolites in Human-GEM as discussed in #728
- Fixes(PR #743)
  - Remove duplicate branched-chain alpha-ketoacid dehydrogenase reaction MAR03748 and MAR03780 as explained in #741 
- Fixes(PR #750)
  - Refine gpr involving BCKDHA (ENSG00000248098), BCKDHB (ENSG00000083123), and TMEM91 (ENSG00000142046) genes, as explained in #742 
    - Remove MAR02532 and MAR02534;
    - Remove MAM02158m, MAM02158n, and MAM02986n;
    - Remove ENSG00000130508 and ENSG00000117592 from the GPR of MAR06523;
    - Add ENSG00000137992 to the GPRs of MAR06416, MAR06419, and MAR06421;
    - Add PMID:11013238 and PMID:31989833 to the references of MAR06523;
    - Removes ENSG00000142046 from the GPRs of MAR06416, MAR06419, MAR06421, and MAR06523 as well as the list of genes in Human-GEM
- Fixes(PR #751)
  - Remove duplicate octanoyl-CoA Beta-oxidation reactions, include MAR06329, MAR06283, MAR06279, MAR05449 and MAR01009 as explained in #747 
- Fixes(PR #752)
  - Remove duplicate Beta-oxidation reaction MAR03422 as explained in #746 
- Fixes(PR #760)
  - Refine GPR of MAR03269 and MAR03380 to `ENSG00000084754 or ENSG00000072506` genes, as discussed in #758 
- Fixes(PR #768)
  - remove inaccurate reaction MAR00789 and duplicate reaction MAR03426 of beta-oxidation of linolenoyl-CoA as explained in #765 
- Fixes(PR #770)
  - Remove ENSG00000115425 from MAR02028, MAR02148, MAR02149, MAR02183, MAR02187 and MAR02207 as explained in #767 
- Fixes(PR #794)
  - Removes MAR00965 and fixes the gpr of MAR00970 as explained in #748 
- Fixes(PR #788)
  - Remove MAR03322 and MAR03296 due to cofactor mismatch and remove MAR04005, and associated MAM00678c and MAM03035c, due to compartment mismatch as reported in #736;
  - Set the GPRs of MAR01176, MAR01181, MAR01218, MAR01222, MAR03446, and MAR03457 to ENSG00000104325 and set the GPRs of MAR01297, MAR03461, and MAR03471 to ENSG00000242612 as reported in #755 
- Fixes(PR #789)
  - Removes MAR05019 for being a duplicate of MAR03142 + MAR03143;
  - Removes MAR04967 for being a duplicate of MAR03143 + MAR03144 + MAR03146;
  - Removes MAR05024 for being a duplicate of MAR03142 + MAR03143 + MAR03144 + MAR03146. All these are discussed in #745 
- Fixes(PR #790)
  - removes EHHADH (ENSG00000113790) from the GPR of MAR03288 as discussed in #756
- Fixes(PR #753)
  - revise inconsistent representation of Thiamine in 2-Oxoacid Dehydrogenase Complexes as explained in #744 
    - Creates MAM20077m to represent 2-(4-carboxy-1-hydroxybutyl)thiamine diphosphate and MAR20173 with `ENSG00000105953 or ENSG00000181192` as GPR
    - Replaces MAM00670m with MAM20077m, replaces MAM01596m with MAM02984m, and removes MAM02039m in MAR04599
    - Creates MAM20078m to represent 2-(2-methyl-1-hydroxypropyl)thiamine diphosphate and MAR20174 with `ENSG00000248098 and ENSG00000083123` as GPR
    - Replaces MAM00824m with MAM20078m, replaces MAM01596m with MAM02984m, and removes MAM02039m in MAR06416
    - Creates MAM20079m to represent 2-(2-methyl-1-hydroxybutyl)thiamine diphosphate and MAR20175 with `ENSG00000248098 and ENSG00000083123` as GPR
    - Replaces MAM00669m with MAM20079m, replaces MAM01596m with MAM02984m, and removes MAM02039m in MAR06419
    - Creates MAM20080m to represent 2-(3-methyl-1-hydroxybutyl)thiamine diphosphate and MAR02176 with `ENSG00000248098 and ENSG00000083123` as GPR
    - Replaces MAM01013m with MAM20080m, replaces MAM01596m with MAM02984m, and removes MAR02039m in MAR06421
    - Creates MAM20081m to represent 2-(1-hydroxypropyl)thiamine diphosphate and MAM20082m to represent S-propanoyldihydrolipoamide
    - Changes MAR03800 to: MAM00671m + MAM02984m + MAM02039m -> MAM20081m + MAM01596m, GPR: `ENSG00000248098 and ENSG00000083123`
    - Creates MAR20177 with `ENSG00000248098 and ENSG00000083123`  as GPR and MAR20178 with `ENSG00000137992` as GPR.
- Fixes(PR #811）
  - Standardize all names of exchange reactions as discussed in #181 
- Feature(PR #574)
  - Add evaluation of gene essentiality using DepMap data.
- Fixes(PR #792)
  - Removes MAR05187 for being a duplicate of MAR03486 + MAR03386;
  - Removes MAR05186 for being a misrepresentation of ALDH3A2;
  - Set GPR of MAR03386 to ENSG00000072210;
  - Removes ENSG00000182591 from the GPR of MAR03486 and remove it from Human-GEM. All these are explained in #775 
- Fixes(PR #793 )
  - Curate duplicate Beta-oxidation pathways for Linoleoyl- and gamma-Linolenoyl-CoA as explained in #793 
    - Removes MAR05358 for being a duplicate of MAR03452 + MAR03453 + MAR03454 + MAR03455
    - Removes MAR05195 for being a duplicate of MAR03456
    - Removes MAR05302 for being a duplicate of MAR03457
    - Removes MAR05229 for being a duplicate of MAR03458
    - Removes MAR05208 for being a duplicate of MAR03281 + MAR03282 + MAR03283
    - Removes MAR05356 for being a duplicate of MAR03275 + MAR03277 + MAR03278 + MAR03279
    - Removes MAR05191 for being a duplicate of MAR03280 + MAR03281 + MAR03282 + MAR03283
    - Removes MAR05123 for being a duplicate of MAR03284 + MAR03285 + MAR03286 + MAR03287
    - Removes MAR05075 for being a duplicate of MAR03288
    - Removes MAR05072 for being a duplicate of MAR03290 + MAR03292 + MAR03293
    - Replaces MAM03274m with MAM00091m in MAR05360
    - Removes MAM03274m for being a duplicate of MAM00091m
    - Removes MAM03653m for being a duplicate of MAM00072m
    - Removes MAM03221m for being a duplicate of MAM00089m
    - Removes MAM03182m for being a duplicate of MAM03009m
    - Removes MAM03978m for being a duplicate of MAM01576m
    - Removes MAM03203m for being a duplicate of MAM01575m
    - Removes MAM02698m for being a duplicate of MAM03021m
    - Removes MAM03650m for being a duplicate of MAM01577m
- Fixes(PR #808)
  - Refine GPRs of Mitochondrial 2-enoyl-CoA Hydration Reactions as explained in #808 
    - Set GPRs of MAR01163, MAR01177, MAR01182, MAR01206, MAR01219, MAR01224, MAR01255, MAR01272, MAR03108, MAR03112, MAR03116, MAR03122, MAR03129, MAR03171, MAR03175, MAR03179, MAR03183, MAR03187, MAR03219, MAR03223, MAR03227, MAR03231, MAR03235, MAR03241, MAR03245, MAR03252, MAR03260, MAR03277, MAR03281, MAR03285, MAR03449, and MAR03453 to ENSG00000084754 (HADHA)
    - Set GPRs of MAR03136, MAR03143, MAR03150, MAR03157, MAR03191, MAR03195, MAR03199, MAR03290, MAR03523, and MAR03528 to `ENSG00000084754 or ENSG00000127884` (HADHA or ECHS1)
    - Set GPRs of MAR03164, MAR03203, MAR03532, MAR03753, MAR03785, and MAR04735 to ENSG00000127884 (ECHS1)
- Fixes(PR #807)
  - Removes MAR04774, MAR04775, and MAR02955c as they seem could not occur in human cells;
  - Updates the references of MAR09417, MAR08760, MAR01472, MAR01038, MAR08761 and MAR08762 as discussed in #754 
- Fixes(PR #805)
  - Curate stereochemistry of phytanic acid metabolism as discussed in #773 
    - Rename `MAM02746e, MAM02746c and MAM02746x` to "(3R)-phytanic acid" and `MAM02747c and MAM02747x` to "(3R)-phytanoyl-CoA"
    - Brought back previously-deprecated MAM03884e, MAM03884c and MAM03884x and renamed them to "(3S)-phytanic acid"
    - Brought back previously-deprecated MAR00659 and MAR01617 (transport reactions for MAM03884)
    - Replace MAM02746c with MAM03884c in MAR03388
    - Change MAR03481 to be MAM02747c + MAM01371c + 2 MAM02040c -> MAM02746x + MAM01597c + MAM02039c + MAM01285c + MAM02751c, GPR: ENSG00000117528, references: PMID:24333844;PMID:33500543
    - Change MAR06779 to be MAM03362c + MAM01371c + 2 MAM02040c -> MAM03384x + MAM01597c + MAM02039c + MAM01285c + MAM02751c, GPR: ENSG00000117528, references: PMID:24333844;PMID:33500543
    - Replace MAM02746x with MAM03884x in MAR03389
    - Rename MAM00655x to "(3R)-2-hydroxyphytanoyl-CoA"
    - Create MAM20083x to represent peroxisomal (2R)-pristanal, and replace MAM00564x ((2S)-pristanal) with MAM20083x in MAR03486
    - Rename MAM02766e, MAM02766c, and MAM02766x to "(2S)-pristanic acid"
    - Brought back previously-deprecated MAR03488 and MAM00077x
    - Replace MAM00564x with MAM20083x in MAR03488, and replace MAM02766x with MAM00077x in MAR03493
    - Create MAM00077c and MAM00077e to represent cytosolic and extracellular (2R)-pristanic acid, and create MAR20179 to represent export of (2R)-pristanic acid from cytosol to extracellular environment
    - Replace MAM02766c with MAM00077c in MAR03390
    - Create MAR20180 to represent exchange of (2R)-pristanic acid
- Fixes(PR #816 )
  - Refine unbalance reactipns as discussed in #814 and #813 
    - change the charge of mets MAM20004n, MAM20006c, MAM20018r, MAM20021i, MAM20024r, MAM20025i, MAM20026r, MAM20027i, MAM20028r, MAM20029i, MAM20030r, MAM20031i, MAM20041r, MAM20042c, MAM20043r, MAM20044c, MAM20056r, MAM20057c from 0 to -1
    - remove MAM02039e in MAR01444; remove MAM02039i in MAR20022, MAR20024, MAR20026, MAR20028 and MAR20030; remove MAM02039r in MAR20023, MAR20025, MAR20027, MAR20029 and MAR20021;
    - add MAM02039m in MAR20111 as a product;  add MAM01422m in MAR20112 as a product; and add MAM02039c in MAR03481 as a product;
    - replace the formula of MAM01657r to "C40H65O7P2"; replace the formula of MAM20082m from None to "C11H23N1O2S2"; replace MAM02041x with MAM01803x in MAR08415; replace MAM02630x with MAM01802x in MAR08415; replace MAM02041x with MAM01803x in MAR03984; replace MAM02630x with MAM01802x in MAR03984; replace MAM02041x with MAM01803x in MAR12372; replace MAM02630x with MAM01802x in MAR12372
- Fixes(PR #815 )
  - Fixes the transport of thiamine Di- and Monophosphate between cytosol and mitochondria as discussed in #783 
    - Created MAR20181 with `ENSG00000125454` as GPR and "PMID:17035501" as references;
    - Created MAR20182 with `ENSG00000125454` as GPR and "PMID:17035501" as references;
    - Created MAR20813 with `ENSG00000125454` as GPR and "PMID:17035501" as references;
    - Removed MAR01788, MAR01789, MAR04205, MAR08745, and MAR08747 for lacking evidence and being redundant with the three new reactions above.
- Fixes(PR #818 ) 
  - resolve the Node 16 warning as discussed in #817 

**I hereby confirm that I have:**

- [ ] Tested my code on my own computer for running the model
- [ ] Selected `develop` as a target branch
- [ ] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
Looking quickly in the changed files, most seem okay. However, I can already flag some changes that have to be verified one by one: there are lines deleted from the `deprecated` files. This would mean that an ID was deprecated, in a previous release, and either un-deprecated now or an accident. Ideally this should never happen - deprecation should be a one-way street. So, for all the reversals of the deprecation, it should be checked that those make sense.

@feiranl you mentioned conflicts betwen feature branches. Were you able to track back to the original pull requests at the source of the confict?

Another thing, could an updated gene essentiality table be provided, [as in the PR for the previous release](https://github.com/SysBioChalmers/Human-GEM/pull/735#issuecomment-1841716531)?

**Comment by feiranl** [comment]
Some IDs were recovered from the deprecated files. I looked into the conflict in yaml file, it should be these reactions:`MAR08415;MAR03984;MAR12372;MAR20021;MAR20022;MAR20023;MAR20024;MAR20025;MAR20026;MAR20027;MAR20028;MAR20029;MAR20030`, because we changed twice. The final format for those reaction should be as in the attached file.[Human_1.19_conflict.txt](https://github.com/SysBioChalmers/Human-GEM/files/15258875/Human_1.19_conflict.txt)
@JHL-452b  Could you list those PRs for these conflicts?

@mihai-sysbio I need to mention that this PR is not done following the guidelines making a release, rather done like merging from feature branch to devel branch, will that be an issue?

**Comment by JHL-452b** [comment]
> Some IDs were recovered from the deprecated files. I looked into the conflict in yaml file, it should be these reactions:`MAR08415;MAR03984;MAR12372;MAR20021;MAR20022;MAR20023;MAR20024;MAR20025;MAR20026;MAR20027;MAR20028;MAR20029;MAR20030`, because we changed twice. The final format for those reaction should be as in the attached file.[Human_1.19_conflict.txt](https://github.com/SysBioChalmers/Human-GEM/files/15258875/Human_1.19_conflict.txt) @JHL-452b Could you list those PRs for these conflicts?

Of course!
Reactions: MAR08415;MAR03984;MAR12372 were modified twice in PR #670  and PR #816.
Reactions: MAR20021;MAR20022;MAR20023;MAR20024;MAR20025;MAR20026;MAR20027;MAR20028;MAR20029;MAR20030 were modified twice in PR #712 and PR #816.

**Comment by mihai-sysbio** [comment]
> @mihai-sysbio I need to mention that this PR is not done following the guidelines of `making a release`, rather done like merging from feature branch to devel branch, will that be an issue? If so, we can igonre this and redo it following the guidelines.

@feiranl the steps in the [release guidelines](https://github.com/SysBioChalmers/Human-GEM/wiki/How-to-make-a-new-release) have to be followed otherwise there will be consequences downstream, such as incorrect versions listed (hinted in the last bullet point).

**Comment by feiranl** [comment]
@mihai-sysbio Thanks! Totally understand. We are planning a new PR following the guidelines. This will be deleted later. But we need to wait until the RAVEN function is merged and the check is back to normal 

@edkerk May I know if there is any plan of when it will be merged?

**Comment by edkerk** [comment]
@feiranl RAVEN 2.9.2 was released yesterday

**Comment by feiranl** [comment]
Nice! thanks Ed. Will close this PR and reopen a new one to release the Human 1.19 @JHL-452b

**Pull request closed without merging**
