### PR TITLE
Add exchange rxns

### PR DESCRIPTION
**Pull request by JonathanRob**
### Main improvements in this PR:

[Addresses Issue #117]

Exchange reactions are added for four metabolites that are present in the extracellular compartment, but do not currently have exchange reactions transporting them to/from the boundary. These changes are implemented with the `curateExchangeRxns2.m` script.

The four metabolites for which exchange reactions are added:
1)  20-hydroxy-arachidonate
2)  chenodiol
3)  LacCer pool
4)  Chylomicron Lipoprotein

In addition, the script addresses the issue of five reactions that involve transport between the boundary compartment and a non-extracellular compartment. The reaction IDs are:
1)  HMR_9736
2)  xenobiotics
3)  arachidonates
4)  steroids
5)  others

Information on the new reactions added to the model is contained in the `newExchangeRxns.tsv` file.

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- [X] Selected `devel` as a target branch

### CODE REVIEW

**Comment by JonathanRob** [comment]
This PR also demonstrates the use of the new `docModelChanges` and `writeModelChanges` functions introduced in PR #118.

**Comment by Hao-Chalmers** [comment]
@JonathanRob this PR looks good.

Would it be better to name the files according to the targeted issue? For example, change filename from `newExchangeRxns.tsv` to `newExchangeRxns_issue117.tsv`, and `curateExchangeRxns2.m` to `curateExchangeRxns_issue117`.

**Comment by JonathanRob** [comment]
@Hao-Chalmers I think that's a good idea. It would make it quite clear which files are associated with which issues/changes.

**Comment by Hao-Chalmers** [comment]
This PR actually adds `8` exchange rxns that are claimed for addressing #117, where there are only 4 exchange rxns were proposed. It would thus be necessary to also mention the other changes (mets and exchange/transport rxns) in #117.

**Comment by JonathanRob** [comment]
@Hao-Chalmers Yes, this PR adds more exchange reactions than the 4 discussed in #117, but these are added for a different reason (as explained in the description of this PR).

The 4 exchange reactions discussed in #117 are to allow exchange of metabolites that are in the extracellular compartment, but do not currently have exchange reactions to/from the boundary. The other exchange reactions added in this PR are for a separate problem, where metabolites are being transported to/from the boundary from a non-extracellular compartment. Since this was not the topic of #117, I don't think there's a need to discuss these other reaction changes there.

**Pull request merged**
