### PR TITLE
Fix duplicate metabolites identified by PubChem IDs(2)

### PR DESCRIPTION
**Pull request by JHL-452b**
#### Main improvements in this PR:

As discussed in https://github.com/SysBioChalmers/Human-GEM/issues/622
- remove rxns `MAR04506`
- change KEGG ID annotations for `MAM01230c`, `MAM02676c`, `MAM02676m`, `MAM02676r`, `MAM02676e`, `MAM02647x`, `MAM03021m`, `MAM03021x`, `MAM00531c`, `MAM00531n`, `MAM02678c`, `MAM02678m`, `MAM02678x`, `MAM02678r`, `MAM02679e`
- replace mets

|old ID|new ID| 
|-----------------|-----------------|
|MAM03540c| MAM01729c|
|MAM03540e| MAM01729e|

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Review by feiranl — APPROVED** [review]
LGTM!

**Comment by haowang-bioinfo** [comment]
it seems this PR introduced bug into Yaml file that started to fail in import/export cycle, better fix it before further merging

**Comment by feiranl** [comment]
> @feiranl it seems this PR introduced bug into Yaml file that started to fail in import/export cycle, better fix it before further merging

This bug was caused by the missing two lines in the newly added met, which was introduced by the merging develop branch into this feature branch. This bug has been fixed in #649

**Comment by haowang-bioinfo** [comment]
yes, very good

**Pull request merged**
