### PR TITLE
fix: merge duplicated long-chain fatty acyl-CoA metabolites

### PR DESCRIPTION
**Pull request by JonathanRob**
### Main improvements in this PR:
Issues #268 and #269 identified two long-chain fatty acyl-CoA metabolites (Undecanoyl-CoA and Tridecanoyl-CoA, respectively) that were duplicated in the model, and not identified earlier due to a difference in the "CoA" component being written out as "Coenzyme A" in the metabolite names. @Hao-Chalmers identified an additional 5 long-chain fatty acyl-CoAs that were duplicated in the same manner (see #268).

This PR removes the duplicated metabolites, and updates some of the annotation information associated with the remaining version of the metabolites.

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- ~[ ] Passed `testYamlConversion` check **<-- This seems like redundant information that should be handled automatically**~
- [X] Selected `develop` as a target branch

### CODE REVIEW

**Comment by Hao-Chalmers** [comment]
quick comments:
- the check of `testYamlConversion` is to ensure lossless conversion between `yaml` and `mat` files. As a Matlab function, it cannot be conviniently incorporated into GH actions (let me know if I were wrong)
- start a new `deprecatedMetabolites.tsv` file under `/data` folder to host the rows removed from `metabolites.tsv`

**Comment by JonathanRob** [comment]
Ah, ok my mistake, I thought it was referring to a python script. But yeah, if its a Matlab script then no problem.

**Comment by Hao-Chalmers** [comment]
It's different from `sanityCheck`, which is to ensure the compatibility with `cobrapy` and `YAMLLint`.

**Comment by mihai-sysbio** [comment]
`testYamlConversion` is now performed via GH action as a result of #286.

**Comment by JonathanRob** [comment]
Fantastic, thank you @mihai-sysbio!

**Comment by JonathanRob** [comment]
I have now added the deprecated metabolites (and their annotation information) to the new `deprecatedMetabolites.tsv` file.

**Review by Hao-Chalmers — APPROVED** [review]
very nice

**Pull request merged**
