### PR TITLE
feat: enable `sanityCheck.py` to check unused mets and genes

### PR DESCRIPTION
**Pull request by haowang-bioinfo**
#### Main improvements in this PR:
This PR improves GH actions in `sanityCheck.py` by enabling detection of unused metabolites 

**I hereby confirm that I have:**
- [x] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [ ] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by haowang-bioinfo** [comment]
Note that the failed `Yaml validation` GH action in this PR is not a failure, instead it correctly reported existing error reported in #525 and fixed by #555.

**Comment by mihai-sysbio** [comment]
This validation already runs on a Docker container that uses Memote, so how about using a Memote tests instead, i.e. https://memote.readthedocs.io/en/latest/autoapi/test_consistency/index.html#test_consistency.test_find_disconnected . For inspiration, have a look at [how this is done in _standard-GEM-validation_](https://github.com/MetabolicAtlas/standard-GEM-validation/blob/main/tests/memote.py). The nice this is that once this would be implemented, more tests could be considered.

**Comment by feiranl** [comment]
also check unused genes by checking the rxnGeneMat

**Comment by haowang-bioinfo** [comment]
> also check unused genes by checking the rxnGeneMat

checking of unused genes and metabolites are both [enabled](https://github.com/SysBioChalmers/Human-GEM/pull/556/files)

**Review by feiranl — APPROVED** [review]
LGTM!

**Pull request merged**
