### PR TITLE
fix: pmids

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:
The reaction references field is inconsistent. This PR aims to update this field by:
- [x] removing uniprot ids
- [x] removing omim ids
- [x] removing hmdb ids
- [x] using only pmids
- [x] formatting the field correctly, ie `PMID:\d+` separated by `;`
- [x] highlight broken references by having the field start with `?? `

**I hereby confirm that I have:**

- [ ] Tested my code on my own computer for running the model
- [x] Selected `develop` as a target branch

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
I'm thinking this PR is easier to review in stages, so I'll take a break for an intermittent review; please feel free to continue the work with more commits on the same branch.

**Comment by mihai-sysbio** [comment]
According to the [documentation](http://co.mbine.org/specifications/sbml.level-3.version-2.core.release-2.pdf), looking for `publication` or `pubmed`, the closest example I found is:
image

In `Human-GEM.xml` this is stored as:
```
      <reaction metaid="R_HMR_3905" sboTerm="SBO:0000176" id="R_HMR_3905" reversible="false" fast="false" fbc:lowerFluxBound="FB2N0" fbc:upperFluxBound="FB3N1000">
        <notes>
          <body xmlns="http://www.w3.org/1999/xhtml">
            <p>Confidence Level: 0</p>
            <p>AUTHORS: PMID:10868354;PMID:12491384;PMID:12818203;PMID:14674758;PMID:15289102;PMID:15299346;PMID:15327949;PMID:15682493;PMID:15713978</p>
          </body>
        </notes>
```

based on `Human-GEM.yml`

```
      - references: "PMID:10868354;PMID:12491384;PMID:12818203;PMID:14674758;PMID:15289102;PMID:15299346;PMID:15327949;PMID:15682493;PMID:15713978"
```

To me, the format `PMID:\d+` is a step forward in the right direction, and it is unclear how much further we can progress at this stage. Therefore, the scope of this PR is limited to bringing all fields to this format.

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio I wonder how could "broken references" be determined?

**Comment by mihai-sysbio** [comment]
> @mihai-sysbio I wonder how could "broken references" be determined?

I could not find these "broken" references by PMID nor DOI. Occasionally it is because they are printed books, and they have only ISBN.

**Comment by mihai-sysbio** [comment]
Perhaps it would make sense to add a `- notes: ""` field for the reactions where the reference doesn't match the fixed PMID.

**Comment by Hao-Chalmers** [comment]
yes, it's possible have a field `rxnNotes` that is a non-mandatory one defined in [RAVEN](https://github.com/SysBioChalmers/RAVEN/issues/184).

**Comment by mihai-sysbio** [comment]
@Hao-Chalmers I suspect `rxnNotes` is a Matlab field that is not mapped to the `yml` format used in the `develop` branch - or is it?

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio this field is possible to be mapped to `yml` file if needed.

**Comment by JonathanRob** [comment]
Another option is to add the `rxnNotes` field to the reaction annotation file. However, that would mean that the field would not be present in the `yml` model file.

**Comment by Hao-Chalmers** [comment]
The corrections are huge in this PR - this is great! Is it okay to be merged? @mihai-sysbio

**Review by Hao-Chalmers — APPROVED** [review]

**Comment by mihai-sysbio** [comment]
> Is it okay to be merged?

I still have a few hundred corrections, I think. There is a checklist at the beginning of the PR where I'm keeping track of the subtasks. When they're done, I will mark the PR as "ready for review" (non-draft).

**Comment by Hao-Chalmers** [comment]
fantastic

**Comment by mihai-sysbio** [comment]
I've finished going through the `references` fields. I haven't created any `notes` or `rxnNotes` field - only highlighted relevant cases as broken references. There are 196 such cases in the 12673, but since these include repetitions, I would guess the number of references to be looked up to be half that.

**Comment by Hao-Chalmers** [comment]
> I propose to raise an issue for fixing the remaining issues, easily identifiable when looking for - references: "??.

Great idea, please proceed to making one.

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio can you merge `develop` into this PR so that it can be conveniently merge back.

**Comment by mihai-sysbio** [comment]
@Hao-Chalmers surre, let me know if the above commit didn't do the trick.

**Comment by Hao-Chalmers** [comment]
good job! @mihai-sysbio

**Pull request merged**
