### PR TITLE
fix-gene: remove non-transporter genes - updated

### PR DESCRIPTION
**Pull request by haowang-bioinfo**
### Main improvements in this PR:
* remove **20** non-transporter genes from `Transporter reactions`, as proposed in #444

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
See my comment in [#444 ](https://github.com/SysBioChalmers/Human-GEM/issues/444#issuecomment-1378199203) - I'm worried that we might be moving too fast here.

**Review by johan-gson — APPROVED** [review]
It was difficult to see the exact changes from last time, but I think you thought it through - I will not go over everything again. Good job!

**Comment by haowang-bioinfo** [comment]
Simulation checks with models before and after these deletions showed exactly the same growth rates.

**Comment by JonathanRob** [comment]
> simulation checks with models before and after these deletions were conducted and showed exactly the same growth rates

Why would removing genes change simulation results? Unless you're using an enzyme-constrained model, I don't quite understand how it would influence flux at all (assuming by "simulation" you mean FBA).

**Comment by haowang-bioinfo** [comment]
> Why would removing genes change simulation results? Unless you're using an enzyme-constrained model, I don't quite understand how it would influence flux at all (assuming by "simulation" you mean FBA).

yes, now it's just FBA that gave the same results since stoichiometric was not changed. As just commented in #426, a systematic checking code would be needed as reaction addition/removal may happen in the future.

**Comment by feiranl** [comment]
Gene essentiality analysis should performed in terms of removing genes? The check function is coming.

**Comment by haowang-bioinfo** [comment]
> Gene essentiality analysis should performed in terms of removing genes?

agree

**Comment by johan-gson** [comment]
If you want I can do the gene essentiality part - I recently did this for the single-cell modeling paper, so I know how to do it and have the code on the cluster etc. set up for this. I can do it in 1-2 weeks (or later), I don't know the status of the model, when it will be ready.

**Comment by johan-gson** [comment]
But don't expect any large changes to the prediction power :)

**Pull request merged**
