### PR TITLE
fix: remove membrane transporter SLC22A5 from carnitine shuttle

### PR DESCRIPTION
**Pull request by PkiwiBird**
excluded gene ENSG00000197375 from gene reaction rule of reaction MAR02590, as discussed in #279.

### CODE REVIEW

**Review by Hao-Chalmers — COMMENTED** [review]
@PkiwiBird the change looks good.

Please rename model file `Human-GEM.yml.txt` back to `Human-GEM.yml`.

**Comment by mihai-sysbio** [comment]
This issue resolves #279.

**Comment by mihai-sysbio** [comment]
There has been an unintentional rename that should be addressed:

**Review by Hao-Chalmers — APPROVED** [review]

**Review by JonathanRob — APPROVED** [review]
Thanks for pointing this out and fixing it, @PkiwiBird!

**Pull request merged**
