### PR TITLE
add Alpha subunits of sodium channel genes to MAR01527

### PR DESCRIPTION
**Pull request by Devlin-Moyer**
#### Main improvements in this PR:
As proposed in #583, replaces the existing GPR of `MAR01527` with `ENSG00000144285 or ENSG00000136531 or ENSG00000153253 or ENSG00000007314 or ENSG00000183873 or ENSG00000136546 or ENSG00000196876 or ENSG00000169432 or ENSG00000185313 or ENSG00000168356 or ENSG00000164588 or ENSG00000138622 or ENSG00000186815 or ENSG00000162341 or ENSG00000102452 or (ENSG00000111319 and ENSG00000168447 and ENSG00000166828) or ENSG00000162572` (see [these](https://journals.physiology.org/doi/full/10.1152/ajprenal.00116.2012) [papers](https://www.sciencedirect.com/science/article/pii/S0378111915015735?via%3Dihub#bb0515) re: the ANDed genes near the end; these have been added to the list of references for `MAR01527`)
Also adds new gene entries for all of those genes, since none were already in Human-GEM

Sodium channels consist of large alpha subunits that associate with accessory proteins, such as beta subunits. An alpha subunit forms the core of the channel and is functional on its own. When the alpha subunit protein is expressed by a cell, it is able to form a pore in the cell membrane that conducts Na+ in a voltage-dependent way, even if beta subunits or other known modulating proteins are not expressed. When accessory proteins assemble with α subunits, the resulting complex can display altered voltage dependence and cellular localization. Note that all these added genes encode alpha subunits of sodium channel, none of them encode beta subunit.

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by Devlin-Moyer** [comment]
I can't tell why the YAML validation is failing; in the past, that error message has indicated that there's a gene in Human-GEM.yml that isn't in genes.tsv or visa versa, but as far as I can tell, all genes in genes.tsv are in Human-GEM.yml and visa versa. I'm just gonna wait until [this PR](https://github.com/SysBioChalmers/Human-GEM/pull/635) is merged and see if those changes to the automated tests make the situation any clearer

**Comment by mihai-sysbio** [comment]
Through commit [8cb8f78](https://github.com/SysBioChalmers/Human-GEM/pull/664/commits/8cb8f7848db7d706124b70cf2f8b9782e9f3fc2f) the output of the errors was more detailed, but the side-effect of that is that the reported error is now gone, as expected.

**Review by haowang-bioinfo — APPROVED** [review]
PR message is updated and specified that only alpha subunits are added

**Comment by haowang-bioinfo** [comment]
5 new genes were added, what are they? and why? - this info is missing, should be explicitly documented

**Pull request merged**
