### PR TITLE
fix: refine reactions, reversibility, and GPRs of Isocitrate Dehydrogenase metabolism

### PR DESCRIPTION
**Pull request by haowang-bioinfo**
This PR improves GPRs of isocitrate dehydrogenase reactions, as proposed by #523:
- remove MAR04111, MAR04112, MAR04113, MAR04585, MAR04586, MAR04587, MAR04588, because as reported in #524:
  - MAR00710 is equivalent to MAR04111+MAR04585
  - MAR00712 is equivalent to MAR04113+MAR04587
  - MAR04588 is part of MAR03957
  - MAR03958 is equivalent to MAR04112+MAR04586
- change to reversible reactions for MAR00710, MAR00712, and MAR03958
- change GPRs to
  - `ENSG00000138413`: for MAR0710, MAR0712, 
  - `ENSG00000182054`: for MAR03958
  - `ENSG00000067829 and ENSG00000101365 and ENSG00000166411`: for MAR03957
- associate Rhea IDs to MAR0710, MAR0712, MAR03957, MAR03958

**I hereby confirm that I have:**

- [ ] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [ ] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer please review the [changes](https://github.com/SysBioChalmers/Human-GEM/pull/525/files#diff-3bcecb48b6715ebe7a47ee8984aa5a1d03945d005ca3f9f6e4f8a926e1644eb2) made to Isocitrate Dehydrogenase reactions based on your proposal.

**Review by Devlin-Moyer — APPROVED** [review]

**Comment by haowang-bioinfo** [comment]
@feiranl maybe you can double check this

**Comment by feiranl** [comment]
These commits are not fully documented in the #523 such as MAR03957 removal, and the proposed changes remain such as 
```
The aconitase reaction (citrate <-> isocitrate) can be carried out in
one step:MAR04456
two steps: MAR04458 (citrate <-> cis-aconitate + H2O) and MAR04589 (cis-aconitate + H2O <-> isocitrate)
```
@haowang-bioinfo  could you explain it a little bit? Actually, I am not a fan of removing the multi-step reactions, since it may affect the flux distribution. For example in the mentioned loop `MAR04456: MAR04458 + MAR04589`, what if `citrate` is not converted to isocitrate 100%, but it was converted to cis-aconitate and then it was converted to other metabolites,  then by removing the `MAR04458`, we actually manipulate the flux distribution to fully to `isocitrate`.

**Comment by Devlin-Moyer** [comment]
[all but two of the other reactions that cis-aconitate can participate in](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM01580c) are transport reactions catalyzed by SLC25A1, and all of those reactions have an otherwise equivalent version that uses citrate or isocitrate in place of cis-aconitate, so removing the only sources of cis-aconitate aside from its exchange reaction would probably have no real impact on predicted/possible flux distributions

Reaction ID | Equation | Genes
-----------------|---------------|---------
MAR00125 | citrate [c] + malate [m] ⇔ citrate [m] + malate [c] | SLC25A1
MAR02216 | isocitrate [m] + malate [c] ⇔ isocitrate [c] + malate [m] | SLC25A1
MAR02420 | cis-aconitate [m] + malate [c] ⇔ cis-aconitate [c] + malate [m] | SLC25A1
 |  | 
MAR02220 | citrate [c] + succinate [m] ⇔ citrate [m] + succinate [c] | SLC25A1
MAR02413 | isocitrate [m] + succinate [c] ⇔ isocitrate [c] + succinate [m] | SLC25A1
MAR02418 | cis-aconitate [m] + succinate [c] ⇔ cis-aconitate [c] + succinate [m] | SLC25A1
 |  | 
MAR02405 | AKG [c] + citrate [m] ⇔ AKG [m] + citrate [c] | SLC25A1
MAR02303 | AKG [c] + isocitrate [m] ⇔ AKG [m] + isocitrate [c] | SLC25A1
MAR02416 | AKG [c] + cis-aconitate [m] ⇔ AKG [m] + cis-aconitate [c] | SLC25A1
 |  | 
MAR02406 | citrate [m] + oxalate [c] ⇔ citrate [c] + oxalate [m] | SLC25A1
MAR02414 | isocitrate [m] + oxalate [c] ⇔ isocitrate [c] + oxalate [m] | SLC25A1
MAR02422 | cis-aconitate [m] + oxalate [c] ⇔ cis-aconitate [c] + oxalate [m] | SLC25A1
 |  | 
MAR04971 | PEP [c] + citrate [m] ⇔ PEP [m] + citrate [c] | SLC25A1
MAR06297 | PEP [c] + isocitrate [m] ⇔ PEP [m] + isocitrate [c] | SLC25A1
MAR06298 | PEP [c] + cis-aconitate [m] ⇔ PEP [m] + cis-aconitate [c] | SLC25A1
 |  | 
MAR06286 | AKG [m] + H+ [c] + citrate [c] ⇒ AKG [c] + H+ [m] + citrate [m] | SLC25A1
MAR06289 | AKG [m] + H+ [c] + isocitrate [c] ⇒ AKG [c] + H+ [m] + isocitrate [m] | SLC25A1
MAR06293 | AKG [m] + H+ [c] + cis-aconitate [c] ⇒ AKG [c] + H+ [m] + cis-aconitate [m] | SLC25A1
 |  | 
MAR06287 | H+ [c] + citrate [c] + succinate [m] ⇒ H+ [m] + citrate [m] + succinate [c] | SLC25A1
MAR06290 | H+ [c] + isocitrate [c] + succinate [m] ⇒ H+ [m] + isocitrate [m] + succinate [c] | SLC25A1
MAR06294 | H+ [c] + cis-aconitate [c] + succinate [m] ⇒ H+ [m] + cis-aconitate [m] + succinate [c] | SLC25A1
 |  | 
MAR06288 | H+ [c] + citrate [c] + oxalate [m] ⇒ H+ [m] + citrate [m] + oxalate [c] | SLC25A1
MAR06292 | H+ [c] + isocitrate [c] + oxalate [m] ⇒ H+ [m] + isocitrate [m] + oxalate [c] | SLC25A1
MAR06296 | H+ [c] + cis-aconitate [c] + oxalate [m] ⇒ H+ [m] + cis-aconitate [m] + oxalate [c] | SLC25A1
 |  | 
MAR04964 | H+ [m] + citrate [m] + malate [c] ⇒ H+ [c] + citrate [c] + malate [m] | SLC25A1
MAR06291 | H+ [c] + isocitrate [c] + malate [m] ⇒ H+ [m] + isocitrate [m] + malate [c] | SLC25A1
MAR06295 | H+ [c] + cis-aconitate [c] + malate [m] ⇒ H+ [m] + cis-aconitate [m] + malate [c] | SLC25A1
 |  | 
MAR04972 | citrate [c] + isocitrate [m] ⇔ citrate [m] + isocitrate [c] | SLC25A1
MAR06276 | cis-aconitate [c] + citrate [m] ⇔ cis-aconitate [m] + citrate [c] | SLC25A1
MAR06277 | cis-aconitate [c] + isocitrate [m] ⇔ cis-aconitate [m] + isocitrate [c] | SLC25A1

the only reactions involving cis-aconitate not on this table are the two steps of the reaction catalyzed by aconitase mentioned above (MAR04458 and MAR04589), the exchange reaction (MAR11350), and symport of cis-aconitate and sodium across the cell membrane (MAR099287)

**Comment by haowang-bioinfo** [comment]
> These commits are not fully documented in the https://github.com/SysBioChalmers/Human-GEM/issues/523 such as MAR03957 removal

this commit didn't remove MAR03957, and the removal here includes only 7 reaction that are: MAR04111, MAR04112, MAR04113, MAR04585, MAR04586, MAR04587, MAR04588 (this is stated in the first point of PR message)

> @haowang-bioinfo could you explain it a little bit? Actually, I am not a fan of removing the multi-step reactions, since it may affect the flux distribution. For example in the mentioned loop MAR04456: MAR04458 + MAR04589, what if citrate is not converted to isocitrate 100%, but it was converted to cis-aconitate and then it was converted to other metabolites, then by removing the MAR04458, we actually manipulate the flux distribution to fully to isocitrate.

this PR didn't touch MAR04456, MAR04458, or MAR04589.

**Comment by haowang-bioinfo** [comment]
Regarding the case of `MAR04456: MAR04458 + MAR04589`, in general I'm kind of leaning toward the idea of @feiranl, i.e. retaining the high resolution version to capture all possible fluxes

with the very nice table prepared by @Devlin-Moyer, it seems that the low resolution option is simple and good enough, according to Occam's razor principle

here's one additional piece of evidence that reports [mitochondrial TCA transporter Mtt1](https://ami-journals.onlinelibrary.wiley.com/doi/10.1111/1751-7915.12329) that can [relocate cis-aconitate from to cytosol](https://biocyc.org/META/NEW-IMAGE?type=REACTION&object=TRANS-RXN-375)

**Comment by haowang-bioinfo** [comment]
for resolving the duplication of `MAR04456 vs. MAR04458 + MAR04589`, how about remove `MAR04456`, this would:
1. be the minimum change to the model
2. without affecting listed transport reactions above
3. higher granularity in resolution supporting potential transport of cis-aconitate

what do you think? @Devlin-Moyer @feiranl

**Comment by Devlin-Moyer** [comment]
Sounds good to me

**Comment by haowang-bioinfo** [comment]
> Sounds good to me

okay, implemented in 8e4f2d255ff130b5bc0b538bef5a8a480217a975

**Comment by feiranl** [comment]
I found after this PR, there are three metabolites `MAM02662c, MAM02662m, MAM02662x` (oxalosuccinate)  that are not used in any rxn in the model. I checked this is due to removing rxns `MAR04111,MAR04112,MAR04113,MAR04585,MAR04586,MAR04587,MAR04588`.  According to this PR, they were removed due to parallel or redundant rxns existed. If that is the case, I suppose the met flow should kept the same. we need to check why there are three mets appears as unused?

**Comment by haowang-bioinfo** [comment]
Good spot! you are absolutely right about the three orphan metabolites (MAM02662c, MAM02662m, MAM02662x) that currently do not involve into any reactions.

**Comment by haowang-bioinfo** [comment]
They should be removed while resolving the duplicated IDH rxns but somehow missed, and now fixed in #555.

How did you find this @feiranl? nice to include this check as GH action as well

**Pull request merged**
