### PR TITLE
feat: improve badges in README.md

### LINKED ISSUE #194: feat: tag Human-GEM releases to Zenodo
### Description of the issue:
* According to the [Zenodo discussion](https://github.com/MetabolicAtlas/standard-GEM/issues/14) on `standard-GEM`, a number of advantages could be taken through tagging the model releases to Zenodo. This feature therefore should be included to Human-GEM.

#### Expected feature/value/output:
* [x] Added a DOI badge that always points to the latest release in Zenodo 
* [x] Update `README.md` file to adapt to this change

**I hereby confirm that I have:**
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:
The aim in this PR is to fix #194. At the same time, by adding the `version.txt` file, the version badge will be fixed from `?.?.?` to the right version, once this file ends up on the `master` branch.

**I hereby confirm that I have:**

- [ ] Tested my code on my own computer for running the model
- [x] Selected `devel` as a target branch

### CODE REVIEW

**Comment by Hao-Chalmers** [comment]
Not sure what's wrong with the version badge, which was certainly alright in this morning.

**Comment by mihai-sysbio** [comment]
Oh that's a bit confusing, `version.txt` exists on `master` but not on `devel`.

**Comment by Hao-Chalmers** [comment]
Now the version badge is back to normal.

**Comment by mihai-sysbio** [comment]
So, what about that `version.txt` file then? Should it or should it not be present on `develop`?

**Comment by Hao-Chalmers** [comment]
"files should not be added without necessity." - law of Ockham's razor

**Comment by JonathanRob** [comment]
From what I remember, the problem we encountered with also having the version number/file on the `devel` branch was that it would become outdated unless we merged `master` into `devel`, which I don't think is consistent with the current workflow.

**Comment by mihai-sysbio** [comment]
To resolve this PR, I propose that I remove the file `version.txt` for now, and maybe we can have a discussion about the workflow to see if there is a way to simplify it.

**Comment by Hao-Chalmers** [comment]
Agree to remove the `version.txt` that can only be existed in master branch.

**Comment by mihai-sysbio** [comment]
The `version.txt` file has been removed - it will not be added to `devel` in this PR.

**Review by Hao-Chalmers — APPROVED** [review]

**Pull request merged**
