### PR TITLE
Fix BCKDH Genes and Remove Mito & Nuc Thiocyanate <-> Hypothiocyanite Reactions

### PR DESCRIPTION
**Pull request by Devlin-Moyer**
#### Main improvements in this PR:
As proposed in #742:
- Adds `ENSG00000137992` to the GPRs of `MAR06416`, `MAR06419`, and `MAR06421`
- Removes `MAR02532` and `MAM02158m` 
- Removes `MAR02534`, `MAM02158n`, and `MAM02986n`
- Removes `ENSG00000130508` and `ENSG00000117592` from the GPR of `MAR06523`
- Adds `PMID:11013238` and `PMID:31989833` to the list of references for `MAR06523`
- Removes `ENSG00000142046` from the GPRs of `MAR06416`, `MAR06419`, `MAR06421`, and `MAR06523` as well as the list of genes in Human-GEM

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by Devlin-Moyer** [comment]
ah whoops; the validation is failing because I removed the gene entry for TMEM91 (`ENSG00000142046`) but it's still in the GPRs of `MAR03748` and `MAR03780`, which I missed because I removed those in #743 and forgot that that wasn't merged yet. We can either
1. wait until #743 is merged into `develop` then merge `develop` into here
2. also remove TMEM91 from the GPRs of `MAR03748` and `MAR03780` in this PR

**Comment by haowang-bioinfo** [comment]
would prefer to option1 that makes things easier

**Comment by Devlin-Moyer** [comment]
Apparently `MAR02352` and `MAR02354` were the only reactions that thiocyanate (`MAM2986`) or hypothiocyanite (`MAM02158`) were involved in in the mitochondrial and nuclear compartments, respectively; I'm just going to remove those metabolites, since they also exist in other compartments where there is evidence to support their existence (namely the cytosol and lysosome)

**Review by haowang-bioinfo — APPROVED** [review]
great work

**Pull request merged**
