### PR TITLE
feat: add hart2015 essentiality suite

### PR DESCRIPTION
**Pull request by haowang-bioinfo**
#### Main improvements in this PR:
This PR provides infrastructure of essentiality test suite, as proposed in #390, using Hart2015 datasets with following components:
- `Hart2015_RNAseq.txt`: RNA-seq sequences of Hart2015 cell lines (GEO: GSE75189)
- `Hart2015_TableS2.xlsx`: Calcuated Bayes factors for CRISPR targeted genes
- `getTaskEssentialGenes`: Identify genes essential for different tasks in different tINIT models
- `estimateEssentialGenes`: Generate tINIT models and estimate essential genes
- `evaluateHart2015Essentiality`: Evaluate and compare Hart2015 experimental fitness genes with predicted results

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [ ] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
This is awesome! A quick thought: can the xlsx file be avoided?

**Comment by haowang-bioinfo** [comment]
> A quick thought: can the xlsx file be avoided?

no, not at the moment - would like to retain the original Hart2015 data file intact

**Comment by haowang-bioinfo** [comment]
> I understand - it makes a lot of sense. And since this file will not be modified, it's not going to continuously enlarge the repository.

thanks - yes it probably will never be changed, any modification, such as into a plain-text version (which does make sense), would confuse people

**Comment by mihai-sysbio** [comment]
> infrastructure of essentiality test suite

Is the aim to run the essentiality suite manually in conjunction with every re;lease?

**Comment by haowang-bioinfo** [comment]
> Is the aim to run the essentiality suite manually in conjunction with every re;lease?

yes, the results can be as attached as evaluation for each release besides other applications

**Comment by mihai-sysbio** [comment]
> to present our recent work for community inspection.

To me, this is already done in the `develop` branch.

> it would also be good at some point to look into which PRs led to increased FP, probably by decreasing TN

Why "at some point" and not now when the changes are more fresh?

**Comment by haowang-bioinfo** [comment]
>> to present our recent work for community inspection.
>
> To me, this is already done in the `develop` branch.

the inspection is best achieved by using the model, and community access is mainly through the releases, instead of the `develop` branch that involves so far a small group of people. To me, I have limited knowledge to evaluate every single changes. The best practice probably is to ensure `release early, release often` in a radically transparent way

>> it would also be good at some point to look into which PRs led to increased FP, probably by decreasing TN
>
> Why "at some point" and not now when the changes are more fresh?

sure go ahead please

**Comment by haowang-bioinfo** [comment]
Code example for running essentiality analysis with Hart2015 datasets:


```Matlab
load('Human-GEM.mat');  % or: ihuman = importYaml('Human-GEM.yml');
taskStruct = parseTaskList('metabolicTasks_Essential.txt');
eGenes = estimateEssentialGenes(ihuman, 'Hart2015_RNAseq.txt', taskStruct);
results = evaluateHart2015Essentiality(eGenes);
```

**Review by JonathanRob — APPROVED** [review]
This is really nice, good work @haowang-bioinfo. I agree it's a bit unfortunate with the large-ish .xlsx file, but as @mihai-sysbio says, it won't need to be changed.

**Comment by mihai-sysbio** [comment]
> Code example for running essentiality analysis with Hart2015 datasets:
> it may take 2-4 hours or more, depending on computer's configuration, to complete this analysis on a laptop or desktop.

Shouldn't we add this then to an action that would run for every pull request from `develop` to `main`?

**Comment by haowang-bioinfo** [comment]
> Shouldn't we add this then to an action that would run for every pull request from develop to main?

not sure if this is suitable for GH action, because the computation load is very heavy. Probably know better after solving #635

**Comment by haowang-bioinfo** [comment]
> the last one encounters an error

ah, yes - now `adjust_pvalues` was added from this [repo](https://github.com/JonathanRob/GeneSetAnalysisMatlab) for convenient use

**Comment by feiranl** [comment]
Successfully run and got this result

'cellLine' | 'TP' | 'TN' | 'FP' | 'FN' | 'accuracy' | 'sensitivity' | 'specificity' | 'F1' | 'MCC' | 'Penr' | 'logPenr' | 'PenrAdj' | 'logPenrAdj'
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
'DLD1' | 95 | 2109 | 143 | 223 | 0.85758755 | 0.29874214 | 0.93650089 | 0.34172662 | 0.26721557 | 1.04E-30 | 29.9838919 | 3.11E-30 | 29.5067706
'GBM' | 85 | 2081 | 153 | 250 | 0.84312962 | 0.25373134 | 0.93151298 | 0.29668412 | 0.21515393 | 1.78E-21 | 20.7503043 | 2.67E-21 | 20.5742131
'HCT116' | 113 | 2137 | 130 | 246 | 0.85681645 | 0.31476323 | 0.94265549 | 0.37541528 | 0.3051743 | 3.02E-40 | 39.519913 | 1.81E-39 | 38.7417618
'HELA' | 86 | 2182 | 157 | 202 | 0.86334222 | 0.29861111 | 0.9328773 | 0.32391714 | 0.24962285 | 2.74E-27 | 26.5616613 | 5.49E-27 | 26.2606313
'RPE1' | 63 | 2115 | 175 | 216 | 0.8478007 | 0.22580645 | 0.92358079 | 0.24371373 | 0.16031484 | 6.69E-13 | 12.1747792 | 6.69E-13 | 12.1747792
'all' | 41 | 2308 | 202 | 76 | 0.89417587 | 0.35042735 | 0.91952191 | 0.22777778 | 0.19220101 | 2.19E-15 | 14.6589606 | 2.63E-15 | 14.5797793

**Review by feiranl — APPROVED** [review]
LGTM!

**Pull request merged**
