### PR TITLE
chore: bump workflow dependency version

### PR DESCRIPTION
**Pull request by mihai-sysbio**
#### Main improvements in this PR:

This PR aims to update the dependencies of GH workflows.

**I hereby confirm that I have:**

- [ ] Tested my code on my own computer for running the model
- [x] Selected `develop` as a target branch
- [ ] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
Note: this PR should stay as draft until the `yaml-validation` passes. The current version seems to have problems that are out of our control.

**Comment by mihai-sysbio** [comment]
The problem seems to originate in the `yaml-validation` action, and there is a pending PR for it https://github.com/ibiqlik/action-yamllint/pull/38.

**Review by haowang-bioinfo — APPROVED** [review]
it's okay to step away from [ibiqlik](https://github.com/ibiqlik/action-yamllint), which apears to be very slow

**Comment by mihai-sysbio** [comment]
Thanks for the review @haowang-bioinfo, I've merged this PR.

Indeed, it seemed that there was very little activity in the original repository, which is why I've forked that repository and published that a new GH Action which is used in this PR.

**Comment by haowang-bioinfo** [comment]
> Indeed, it seemed that there was very little activity in the original repository, which is why I've forked that repository and published that a new GH Action which is used in this PR.

probably consider centralizing all used GH actions for convenient maintenance

**Pull request merged**
