### PR TITLE
feat: change compartment abbreviation

### PR DESCRIPTION
**Pull request by smoretti**
**Main improvements in this PR:**

- change Extracellular compartment abbreviation from `s` to `e`, as discussed in #314. Extracellular compartment and chemical species ids have been updated.

**I hereby confirm that I have:**

- [x]  Selected `develop` as a target branch

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
@Hao-Chalmers could you share more details on what more work is required? I read that @JonathanRob mentioned backwards compatibility, but it's hard for me to know specifically where that needs to be addressed.

**Comment by JonathanRob** [comment]
@mihai-sysbio one of my concerns with changing the compartment abbreviation was actually whether this would affect Metabolic Atlas in any way? Since we need to change the actual metabolite IDs, it's not quite as straightforward as if we were changing an external/associated ID.

We also need to determine what to do with the existing IDs. Should they be added to the `metRetired` column in the `metabolites.tsv` file? Or just change them and not modify anything else in the `metabolites.tsv` file (except the metabolite ID, of course)?

We would then just need to check what other functions or data files have hard-coded the compartment abbreviations somewhere within. I don't think there are many cases, but the metabolic task files would of course be one case.

**Comment by JonathanRob** [comment]
@mihai-sysbio ok great suggestions.

> Therefore, my suggestion is to deprecate these identifiers as if they would not be replaced, i.e. to copy the corresponding lines to deprecatedMetabolites.tsv and then do the renaming.

Good idea, we can plan to do that.

> There didn't seem to be anything interesting in the `code` folder pertaining to `s`

My guess is that `x` would be more of an issue. For example, the [`addBoundaryMets`](https://github.com/SysBioChalmers/Human-GEM/blob/main/code/addBoundaryMets.m) function should be updated.

> Should this PR also include the renaming of x to something else (b?) and p to x ?

Yeah, definitely. We should do all the renaming of these at once. I think a change of boundary to `b` would be fine, unless there's some other compartment where `b` would be the more intuitive letter.

**Comment by Hao-Chalmers** [comment]
> @Hao-Chalmers could you share more details on what more work is required? I read that @JonathanRob mentioned backwards compatibility, but it's hard for me to know specifically where that needs to be addressed.

@mihai-sysbio thanks for bring this up. Specially, things should be addressed are, but not limited to:
- align metabolic task files to the change from `s` to `e`
- fix function `addBoundaryMets` while changing `x` to `p`

**Comment by Hao-Chalmers** [comment]
Very good discussions @JonathanRob @mihai-sysbio 

Agree with the proposed plan (copy the corresponding lines to `deprecatedMetabolites.tsv` and then do the renaming). Let's focus on the change from `s` to `e` in this branch and including modification of metabolic task files as well

**Comment by JonathanRob** [comment]
> Let's focus on the change from s to e in this branch 

@Hao-Chalmers I would recommend that we make all the compartment changes together in one branch, or is there some reason that you would prefer to break it up?

**Comment by JonathanRob** [comment]
If it is OK with all of you @smoretti, @Hao-Chalmers, @mihai-sysbio, we can close this PR and I will implement abbreviation changes of all the compartments (extracellular, peroxisome, and boundary) in a new, single branch. This would also avoid having to update this branch with `develop`, which it's currently pretty far behind.

**Comment by Hao-Chalmers** [comment]
> If it is OK with all of you @smoretti, @Hao-Chalmers, @mihai-sysbio, we can close this PR and I will implement abbreviation changes of all the compartments (extracellular, peroxisome, and boundary) in a new, single branch. This would also avoid having to update this branch with develop, which it's currently pretty far behind.

@JonathanRob  sounds good, go ahead please.

**Comment by Hao-Chalmers** [comment]
> @Hao-Chalmers I would recommend that we make all the compartment changes together in one branch, or is there some reason that you would prefer to break it up?

based on lessons learned from previous work, here are some advantages to have each branch with more specific changes:
- clear goal and simple task
- quicker implementing and easier reviewing
- lower cost if made mistakes
- faster looping back from issue/discussion to the merging of implementation PR

**Comment by mihai-sysbio** [comment]
Even though all changes are based on the same rationale, and maybe some of the manual checks will be done only once, it was a good idea to split the work. That being said, if it makes @JonathanRob's life easier, it's fine by me.

**Comment by JonathanRob** [comment]
Ah ok, I think both of you @Hao-Chalmers and @mihai-sysbio make good points about splitting it up, but for simplicity I will combine them into a single branch/PR.

**Comment by JonathanRob** [comment]
Closing this and implementing the changes in #341

**Pull request closed without merging**
