### PR TITLE
fix: correct gene-reaction association

### PR DESCRIPTION
**Pull request by Hao-Chalmers**
### Main improvements in this PR:
This PR is to fix the error reported in #198
* the gene assigned for ganglioside GP1c formation reaction `HMR_8177` was changed from `ST6GALNAC2` (ENSG00000070731) to `ST8SIA5` (ENSG00000101638)
* a citation was assigned to reaction `HMR_8177` based on UniProt annotation to the gene `ST8SIA5`
* a reference was also added to the biosynthesis reactions for gangliosides GD1c (`HMR_8171`) , GT1a (`HMR_8182`) , GQ1b (`HMR_8181`)  and GT3 (`HMR_8180`), which are all catalyzed by the enzyme encoded by `ST8SIA5`. 
* the confidence scores for above reactions were updated as well.

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- [X] Selected `devel` as a target branch

### CODE REVIEW

**Comment by JonathanRob** [comment]
@Hao-Chalmers why was the reaction confidence score set to 2 instead of 4 for the `HMR_8177` reaction?

**Comment by Hao-Chalmers** [comment]
@JonathanRob according to UniProt function annotation to gene [ST8SIA5](https://www.uniprot.org/uniprot/O15466), its association with the synthesis of gangliosides GP1c (reaction `HMR_8177`) was assigned based on sequence similarity, instead of experimental evidence.

**Comment by TunahanCakir** [comment]
@Hao-Chalmers  Thank you for such a quick action!
Yes the revision is in accordance with what I requested.

**Comment by Hao-Chalmers** [comment]
@TunahanCakir we are very appreciated for the contributions from you and others in the research community, for which the Human-GEM aims to serve.

**Review by JonathanRob — APPROVED** [review]

**Pull request merged**
