### PR TITLE
Human 1.14

### PR DESCRIPTION
**Pull request by haowang-bioinfo**
### Main improvements in this PR:
- Fix: remove non-metabolic genes, discovered using the GPT language model, from subsystems :
  - #485 resolves:
    - #481
    - #484
  - #480 resolves:
    - #476
    - #477
    -  #478
  - #474 and #472 resolve:
    - #471
  - #467 resolves:
    - #463
    - #464
    - #465
    - #466 
  - #461 resolves
    - #457
  - #455 resolves:
    - #452
  - #453 resolves:
    - #449
  - #451 resolves:
    - #447
  - #450 resolves:
    - #444
  - #445 resolves:
    - #443
  - #442 resolves:
    - #426
- Feature (PR #482):
  - refactor `extractAllianceGenomeOrthologs` from reading JSON to TSV file, as discussed in [#15](https://github.com/SysBioChalmers/Mouse-GEM/issues/15) of Mouse-GEM
- Feature/Style (PR #479):
  - add @feiranl as a contributor
- Feature (PR #475):
  - improve issue and PR templates 
- Fix(PR #462):
  - add subunit NDUFA7 to complex I, as explained in #446
- Fix (PR #460):
  - correct wrongly associated CHEBI annotation to MAM03882, as reported in Mouse-GEM issue [#21](https://github.com/SysBioChalmers/Mouse-GEM/issues/21)
- Fix (PR #459):
  - changed `subsystems` for 2 exchange rxns, modified name 7 transport rxns, as discussed in #456

### CODE REVIEW

**Review by mihai-sysbio — APPROVED** [review]
Looks good to me!
I've updated the PR body to make it easier to follow.

**Comment by haowang-bioinfo** [comment]
> I've updated the PR body to make it easier to follow.

@mihai-sysbio nice! Would it be possible to assembly the text by by GitHub actions or other automatic methods?

**Comment by mihai-sysbio** [comment]
> @mihai-sysbio nice! Would it be possible to assembly the text by by GitHub actions or other automatic methods?

A quick search through on the GH Action Marketplace didn't yield much, but I want to remember there was a tool that was summarizing PRs in a Markdown file, so that could be used in a custom GH Action.
For the release notes, I know of this: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes /

**Comment by haowang-bioinfo** [comment]
> For the release notes, I know of this: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes/

good to know this!

**Pull request merged**
