### PR TITLE
fix: Add AUH to previously-empty GPRs of MAR05999, MAR08664, and MAR11514

### PR DESCRIPTION
**Pull request by Devlin-Moyer**
#### Main improvements in this PR:
As proposed in #590:
- Adds AUH (`ENSG00000148090`) to the previously empty GPR of `MAR08664`
- make MAR08664 irreversible in direction of hydrolysis
- Adds PMID:29056341 as a reference to `MAR08664`

Also as discussed below:
- Adds RHEA IDs for `MAR08664`
- Adds AUH (`ENSG00000148090`) to the previously-empty GPRs of MAR05999 and MAR11514

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer very nice

could you please also add Rhea id to MAR08664 in the `genes.tsv` file

**Review by haowang-bioinfo — APPROVED** [review]
fantastic

**Comment by feiranl** [comment]
@Devlin-Moyer  Please check wether [MAR11514](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR11514) and [MAR05999](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05999) should also be associated with this gene according to Uniprot annotation.

**Comment by Devlin-Moyer** [comment]
@feiranl yes AUH should be associated with `MAR11514` and `MAR05999`; I can take care of that now

However, while checking that, I found another problem:
`MAR11514` is `H2O [m] + Trans-Delta-2-Glutaryl Coenzyme A [m] ⇒ 3-Hydroxy-Glutaryl Coenzyme A [m]`
`RHEA:68456` is "(_S_)-3-hydroxyglutaryl-CoA <-> 2E-glutaconyl-CoA + H2O"
I verified that "Trans-Delta-2-Glutaryl Coenzyme A" and "2E-glutaconyl-CoA" are two possible names for the same compound, but found that Human-GEM has a different metabolite called "Glutaconyl Coenzyme A": `MAM03613m` ("Trans-Delta-2-Glutaryl Coenzyme A" is `MAM03964m`)
Should I make a separate issue/pull request for dealing with the duplicate glutaconyl-CoA metabolites?

**Comment by haowang-bioinfo** [comment]
> @Devlin-Moyer Please double check wether [MAR11514](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR11514) is for RHEA:68456 and [MAR05999](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05999) is for RHEA:31079 and should be associated with this gene according to Uniprot annotation.

good catch

> @feiranl yes AUH should be associated with MAR11514 and MAR05999; I can take care of that now
Should I make a separate issue/pull request for dealing with the duplicate glutaconyl-CoA metabolites?

this probably can be fixed within this PR

**Comment by haowang-bioinfo** [comment]
> I verified that "Trans-Delta-2-Glutaryl Coenzyme A" and "2E-glutaconyl-CoA" are two possible names for the same compound, but found that Human-GEM has a different metabolite called "Glutaconyl Coenzyme A": MAM03613m ("Trans-Delta-2-Glutaryl Coenzyme A" is MAM03964m)

yes, it does appear that "Trans-Delta-2-Glutaryl Coenzyme A" and "2E-glutaconyl-CoA" are the same compound. 

Regarding "Glutaconyl Coenzyme A" MAM03613m, on the other hand, it involved into hydrolysis with CoA as end product (MAR11521), unlike those catalyzed by AUH. So maybe leave MAM03613m out of this issue

**Review by feiranl — APPROVED** [review]
LGTM!

**Comment by haowang-bioinfo** [comment]
then please also add Rhea ids to MAR11514 and MAR05999 in the `reactions.tsv` file

**Comment by haowang-bioinfo** [comment]
splendid

**Pull request merged**
