### PR TITLE
fix random workflow failures

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:
Local equivalent of #323, aiming to fix the apparently random unexpected `yaml-validation` workflow failures.

**I hereby confirm that I have:**

- [x] Selected `develop` as a target branch

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
Commit 1a8041c adds a caching mechanism where the model folder is cached with the commit SHA as the key, thus leading to cache refresh with every new commit. This seems to have resolved the problem.

**Comment by Hao-Chalmers** [comment]
then if the increase to `fetch-depth` is still necessary?

**Comment by mihai-sysbio** [comment]
@Hao-Chalmers a depth of `1` is the default value, so I edited the history of this branch to remove that commit.

**Review by Hao-Chalmers — APPROVED** [review]
Base on the comparison between #323 and #324, it appears that the recent GH action failure is cache-related issue and can be fixed by forced cache refreshing using commit SHA as key.

**Pull request merged**
