### PR TITLE
refactor: adjust `extractAllianceGenomeOrthologs` from reading JSON to TSV file

### PR DESCRIPTION
**Pull request by haowang-bioinfo**
### Main improvements in this PR:
* adjust `extractAllianceGenomeOrthologs` from reading JSON to TSV format ortholog pairs, as discussed in [#15](https://github.com/SysBioChalmers/Mouse-GEM/issues/15) of Mouse-GEM and switch to this [branch](https://github.com/SysBioChalmers/Mouse-GEM/commit/6580599187b2e34a0114e0b28987240361396dc3) to test this PR.

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch

### CODE REVIEW

**Review by mihai-sysbio — CHANGES_REQUESTED** [review]
Looks good, but I'd like to run this myself - could you share a code snippet of how to do that?

I'll request changes because the function documentation still mentions JSON on line 3.

**Comment by haowang-bioinfo** [comment]
> Looks good, but I'd like to run this myself - could you share a code snippet of how to do that?

here's the code that can run the test:
```matalb
OGpairs = extractAllianceGenomeOrthologs('human2MouseOrthologs.tsv')
```
Note: Mouse-GEM repo should be cloned and `Add to Path` in Matlab

> I'll request changes because the function documentation still mentions JSON on line 3.

function documentation is updated in 78c4f7dfce7091a69187bf7719f258661f90dfbe

**Review by mihai-sysbio — APPROVED** [review]
I've tested this and it works nicely.

Any thoughts on the capitalization of the symbols? I see many occurrences where this is the only difference between `from` and `to`.

**Comment by haowang-bioinfo** [comment]
> Any thoughts on the capitalization of the symbols? I see many occurrences where this is the only difference between `from` and `to`.

true, this is the way of naming symbols between human and mouse (even rat), i.e. keep everything identical but capitalization. The purpose is to keep evident association in between.

**Pull request merged**
