### PR TITLE
feat: add compartment info from deeploc2 prediction

### PR DESCRIPTION
**Pull request by feiranl**
### Main improvements in this PR:
* compartment information is added as discussed in #436
  - subcellular locations of metabolic genes were predicted using [DeepLoc2]([10.1093/nar/gkac278](https://doi.org/10.1093/nar/gkac278)) using the default parameter
  - compartment info for genes which doesn't have localization annotation as in pull request #437 were combined and integrated into `genes.tsv` with `compDataSource` was denoted as `DeepLoc2`

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch

*Note: replace [ ] with [X] to check the box. PLEASE DELETE THIS LINE*

### CODE REVIEW

**Comment by haowang-bioinfo** [comment]
very good!

**Comment by feiranl** [comment]
Then those corresponding rxns should involve both extracellular and cytosol metabolites?

**Comment by haowang-bioinfo** [comment]
> Then those corresponding rxns should involve both extracellular and cytosol metabolites?

do you mean the enzymes are potential transporters?

**Review by haowang-bioinfo — APPROVED** [review]

**Comment by feiranl** [comment]
> > Then those corresponding rxns should involve both extracellular and cytosol metabolites?
> 
> do you mean the enzymes are potential transporters?

Could be but not necessarily. It could functions as to degrade extracellular metabolites into extracellular molecules that can be transported into cytosol, or just perform cytosol conversions. So I say when the protein is annotated to cell membrane, so either cytosol or extracellular compartment for metabolites in the corresponding rxns should be ok.

**Pull request merged**
