### PR TITLE
Feat: added smiles and inchi of metabolites

### PR DESCRIPTION
**Pull request by JHL-452b**
#### Main improvements in this PR:

This PR added a document of SMILEs and inchi information of metabolites to `data/modelCuration` as discussed in [#728 ](https://github.com/SysBioChalmers/Human-GEM/issues/728). To ensure completeness, in addition to SMILEs, inchi information is also added to TSV.

**I hereby confirm that I have:**

- [ ] Tested my code on my own computer for running the model
- [X] Selected `deXvelop` as a target branch
- [ ] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by haowang-bioinfo** [comment]
@JHL-452b look nice

In order to properly evaluate this PR, please provide more detail information about data source and manipulation, preferably with extraction code

**Comment by JHL-452b** [comment]
> In order to properly evaluate this PR, please provide more detail information about data source(s) and manipulation, preferably with extraction code

### Data source(s) and main manipulation:
Firstly, I downloaded and collated metabolite information from various databases(including KEGG, ChEBI, PubChem(Api), HMDB, Lipidmaps, Recon3D). The collected information of metabolites contains ID and SMILEs, so I used ID mapping relationship in `metabolites.tsv` to extract SMILEs. Then, the function of MolToInchiKey and MolToInchi in RDKit was used to convert SMILEs to inchiKey and inchi, respectively.

### Results
|   |metabolites| SMILEs| inchiKey| inchi|
|----------------|----------------|--------------------|-----------------------|---------------------|
|All| 8460| 7141| 6435| 6435|
|Unique| 4163| 3399| 2973| 2973|

> just curious about the column of `InChIkey` which was not mentioned in #728, if it's redundant to `InChI`?

Inchi is better for accurately representing and comparing chemical substances, while InChIKeys could serve mainly as shortcuts that point back to the original InChI. So I think using both together provides optimal capabilities - InchIKey for fast lookup and matching, with the original InchI storing the richer chemical structure details. 

Of course, it's just my opinion.

**Comment by haowang-bioinfo** [comment]
> Inchi is better for accurately representing and comparing chemical substances, while InChIKeys could serve mainly as shortcuts that point back to the original InChI. So I think using both together provides optimal capabilities - InchIKey for fast lookup and matching, with the original InchI storing the richer chemical structure details.

thanks for the info, sounds good to have both Inchi and InChIKeys

> Firstly, I downloaded and collated metabolite information from various databases(including KEGG, ChEBI, PubChem(Api), HMDB, Lipidmaps, Recon3D). The collected information of metabolites contains ID and SMILEs, so I used ID mapping relationship in metabolites.tsv to extract SMILEs. Then, the functions of MolToInchiKey and MolToInchi in RDKit was used to convert SMILEs to inchiKey and inchi, respectively.

would be nice to also have the relevant code uploaded to `code/modelCuration` as references

**Comment by feiranl** [comment]
@JHL-452b It would be great if you could upload the code into the `code/modelCuration` as suggested by Hao. Then we can start review this. Thanks!

**Comment by JHL-452b** [comment]
Sorry late for uploading the code. Thanks for reminding.

**Comment by haowang-bioinfo** [comment]
@JHL-452b thanks

**Review by haowang-bioinfo — APPROVED** [review]

**Pull request merged**
