### PR TITLE
Fix Peroxisomal Cofactor Transport Reactions

### PR DESCRIPTION
**Pull request by Devlin-Moyer**
#### Main improvements in this PR:

As proposed in #640:
- Removes `MAR07785` for being a less accurate/complete duplicate of `MAR04908`
- Removes `MAR07775` because there's no evidence that NADH is transported across the peroxisomal membrane
- Removes `MAR07788` because there’s no evidence that FADH<sub>2</sub> is transported across the peroxisomal membrane
- Removes `MAR04915`, `MAR07771`, `MAR07782`, `MAR07783`, and `MAR07790` because the only known peroxisomal transporters of those metabolites catalyze antiport, not uniport
- Changes `MAR03473` to be ADP [c] + AMP [x] <-> ADP [x] + AMP [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20115`: AMP [c] <-> AMP [x], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20116`: ADP [c] <-> ADP [x], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new FMN [x] metabolite `MAM01828x`
- Adds new reaction `MAR20117`: FAD [x] + H<sub>2</sub>O [x] -> FMN [x] + AMP [x], GPR: `ENSG00000112874`, reference: `PMID:22185573`
- Adds new reaction `MAR20118`: FMN [c] + CoA [x] <-> FMN [x] + CoA [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20119`: FMN [c] + FAD [x] <-> FMN [x] + FAD [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20120`: FMN [c] + NAD<sup>+</sup> [x] <-> FMN [x] + NAD<sup>+</sup> [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20121`: FMN [c] + AMP [x] <-> FMN [x] + AMP [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20122`: FMN [c] + ADP [x] <-> FMN [x] + ADP [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20123`: FAD [c] + CoA [x] <-> FAD [x] + CoA [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20124`: FAD [c] + NAD<sup>+</sup> [x] <-> FAD [x] + NAD<sup>+</sup> [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20125`: FAD [c] + AMP [x] <-> FAD [x] + AMP [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20126`: FAD [c] + ADP [x] <-> FAD [x] + ADP [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20127`: NAD<sup>+</sup> [c] + CoA [x] <-> NAD<sup>+</sup> [x] + CoA [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20128`: NAD<sup>+</sup> [c] + AMP [x] <-> NAD<sup>+</sup> [x] + AMP [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20129`: NAD<sup>+</sup> [c] + ADP [x] <-> NAD<sup>+</sup> [x] + ADP [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20130`: AMP [c] + CoA [x] <-> AMP [x] + CoA [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`
- Adds new reaction `MAR20131`: ADP [c] + CoA [x] <-> ADP [x] + CoA [c], GPR: `ENSG00000100372`, reference: `PMID:22185573`

**I hereby confirm that I have:**
- [x] Tested my code on my own computer for running the model
- [x] Selected `develop` as a target branch
- [x] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by Devlin-Moyer** [comment]
I can't figure out why the YAML conversion checks are failing; I feel like that's usually due to a formatting issue where like I didn't indent a particular line right or misspelled one of the field names, but I keep failing to see any of those kinds of typos.

**Comment by haowang-bioinfo** [comment]
yes there are formatting issues that should be due to the missing "eccodes" fields from MAR20117 onward

**Comment by Devlin-Moyer** [comment]
aha thanks for spotting that; I'll fix it when I get back to my computer

also I've been editing it directly with a text editor cuz I don't know Matlab and found out the hard way that Cobrapy doesn't output YAML files in this exact format and it seemed easier (if more tedious) to just do it by hand than figure out what changes I'd need to make Cobrapy's yaml output

**Review by feiranl — APPROVED** [review]
LGTM! Good job!

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer great job! a small thing: MAR20117 is not fully balanced - now fixed in 3eb081774fe08db4969ff629a74880e52cfa9f15

@feiranl probably at some point it's good to have a mass/charge balance check for new reactions

**Review by haowang-bioinfo — APPROVED** [review]

**Comment by feiranl** [comment]
Yes, I totally agree. A new issue has been opened to address this.

**Comment by Devlin-Moyer** [comment]
ah thanks for catching that. and yea, incorporating that into the automated checks would be very useful, because it's easy to miss a few protons like I did here, and #670 would've been way easier to resolve if one of the automated checks had told us that one of those edits un-balanced a reaction

**Pull request merged**
