### PR TITLE
Fix/mito nuc trans

### PR DESCRIPTION
**Pull request by Devlin-Moyer**
#### Main improvements in this PR:

As proposed in #694:
- Creates new gene entries for `ENSG00000171612` (name: SLC25A33) and `ENSG00000114120` (name: SLC25A36)
- Makes `MAR08301` reversible and change its GPR to `ENSG00000171612`
- Removes `MAR07823`, `MAR07926`, `MAR09019` and `MAR04843`
- Creates new reaction `CTP [c] + CDP [m] <-> CTP [m] + CDP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + CMP [m] <-> CTP [m] + CMP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + dCTP [m] <-> CTP [m] + dCTP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + dCDP [m] <-> CTP [m] + dCDP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + dCMP [m] <-> CTP [m] + dCMP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + GTP [m] <-> CTP [m] + GTP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + GDP [m] <-> CTP [m] + GDP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + GMP [m] <-> CTP [m] + GMP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + dGTP [m] <-> CTP [m] + dGTP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + dGDP [m] <-> CTP [m] + dGDP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + dGMP [m] <-> CTP [m] + dGMP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + ITP [m] <-> CTP [m] + ITP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + IDP [m] <-> CTP [m] + IDP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + IMP [m] <-> CTP [m] + IMP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + UTP [m] <-> CTP [m] + UTP [c]`, GPR: `ENSG00000114120 or ENSG00000171612`
- Creates new reaction `CTP [c] + UDP [m] <-> CTP [m] + UDP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + UMP [m] <-> CTP [m] + UMP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + dUTP [m] <-> CTP [m] + dUTP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + dUDP [m] <-> CTP [m] + dUDP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `CTP [c] + dUMP [m] <-> CTP [m] + dUMP [c]`, GPR: `ENSG00000114120`
- Creates new reaction `UTP [c] + CDP [m] <-> UTP [m] + CDP [c]`, GPR: `ENSG00000171612`
- Creates new reaction `UTP [c] + dCTP [m] <-> UTP [m] + dCTP [c]`, GPR: `ENSG00000171612`
- Creates new reaction `UTP [c] + dCDP [m] <-> UTP [m] + dCDP [c]`, GPR: `ENSG00000171612`
- Creates new reaction `UTP [c] + GTP [m] <-> UTP [m] + GTP [c]`, GPR: `ENSG00000171612`
- Creates new reaction `UTP [c] + GDP [m] <-> UTP [m] + GDP [c]`, GPR: `ENSG00000171612`
- Creates new reaction `UTP [c] + dGTP [m] <-> UTP [m] + dGTP [c]`, GPR: `ENSG00000171612`
- Creates new reaction `UTP [c] + dGDP [m] <-> UTP [m] + dGDP [c]`, GPR: `ENSG00000171612`
- Creates new reaction `UTP [c] + ITP [m] <-> UTP [m] + ITP [c]`, GPR: `ENSG00000171612`
- Creates new reaction `UTP [c] + dTTP [m] <-> UTP [m] + dTTP [c]`, GPR: `ENSG00000171612`
- Creates new reaction `UTP [c] + dTDP [m] <-> UTP [m] + dTDP [c]`, GPR: `ENSG00000171612`
- Creates new reaction `UTP [c] + UDP [m] <-> UTP [m] + UDP [c]`, GPR: `ENSG00000171612`
- Creates new reaction `UTP [c] + dUTP [m] <-> UTP [m] + dUTP [c]`, GPR: `ENSG00000171612`
- Creates new reaction `CTP [c] <-> CTP [m]`, GPR: `ENSG00000114120 or ENSG00000171612`
- Creates new reaction `GTP [c] <-> GTP [m]`, GPR: `ENSG00000114120 or ENSG00000171612`
- Creates new reaction `UTP [c] <-> UTP [m]`, GPR: `ENSG00000114120 or ENSG00000171612`

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by feiranl** [comment]
-- | --
dTTP [c] <-> dTTP [m] | ENSG00000171612

may be missing?

**Comment by feiranl** [comment]
MAR20138 and MAR20139 are same. Please remove one.

**Review by feiranl — APPROVED** [review]
LGTM excep the duplicated rxn mentioned.

**Comment by haowang-bioinfo** [comment]
good job!

minor thing: the new reaction MAR20166 `dTTP [c] <-> dTTP [m]` listed in #694 was somehow missing here in the PR message

**Review by haowang-bioinfo — APPROVED** [review]

**Comment by Devlin-Moyer** [comment]
MAR08301 already represented uniport of dTTP between the cytosol and mitochondria, so I didn't have to make a new reaction for it. I did have to make it reversible and associate it with SLC25A33, which is the second change listed in the PR message.

**Comment by haowang-bioinfo** [comment]
wait

**Comment by Devlin-Moyer** [comment]
oh whoops that is right; MAR20166 shouldn't have been added cuz it is redundant with MAR08301. I can fix that in like an hour or two

**Comment by haowang-bioinfo** [comment]
> oh whoops that is right; MAR20166 shouldn't have been added cuz it is redundant with MAR08301. I can fix that in like an hour or two

ok, then take away existing MAR20166 and turn MAR20167 into new MAR20166, make them consistent with reactons.tsv please

**Comment by haowang-bioinfo** [comment]
I wonder how this duplication pair (MAR20166 vs. MAR08301) was escaped from the memote test, any ideas @mihai-sysbio

**Pull request merged**
