### PR TITLE
Fix: standardize EC codes and remove orphan metabolites

### PR DESCRIPTION
**Pull request by JonathanRob**
#### Standardize reaction EC codes
As described in issue #127, the model EC codes (in the `eccodes` field) have inconsistent formats and types, such as spaces, colons, and/or TCDB codes.

This PR standardizes the model `eccodes` field as follows:
- All spaces are removed
- All `EC:` or `EC` prefixes are removed
    - e.g., `EC:1.1.1.1` becomes `1.1.1.1`
- All `TCDB:` IDs are removed
    - these IDs are instead added to a new field in the `humanGEMRxnAssoc.JSON` reaction annotation file

#### Removal of three orphan metabolites
The metabolites `m10018m` and `m10018p`, corresponding respectively to mitochondrial and peroxisomal versions of `5-Hydroxy-2-oxo-4-ureido-2,5-dihydro-1H-imidazole-5-carboxylate`, and `m10019n` which is the version of `5alpha-Pregnan-20alpha-ol-3-one` in the nucleus, have now been removed from the model. These metabolites have also been removed from the `humanGEMMetAssoc.JSON` metabolite annotation file.

These three metabolites were introduced from the iHsa model in PR #140, but do not participate in any reactions ("orphan" metabolites).

#### Update/fix of `annotateModel` function
- Line 204 was commented-out in commit b603e99 due to an error that can not be reproduced, and therefore has been re-incorporated.
- Now recognizes and builds proper Miriam fields for reaction TCDB IDs

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- [X] Selected `devel` as a target branch

### CODE REVIEW

**Comment by Hao-Chalmers** [comment]
When tracking changes to `HumanGEM.yml`, this message appears: "5,492 additions, 5,516 deletions not shown because the diff is too large".

**Comment by JonathanRob** [comment]
@Hao-Chalmers yes, unfortunately, the `eccodes` field of thousands of reactions has been updated, leading to a large diff that GitHub web refuses to display. You can view the diff on the command line, though.

**Comment by Hao-Chalmers** [comment]
Some comments to ensure transparent track of changes:
- The detachment of TCDB codes from Yaml and addition to JSON look good. But it is impossible to properly track and check of this modificaiton, until the script is provided
- A bunch of EC codes were edited by removing "spontaneous", which however are not recorded and will be difficult to follow up. A log file containing the rxn ids of these entries would be convinient for revisiting these cases in the future
- Among the reformatted of EC codes, three entires with identical value were found problematic in lines: 285871, 285952, 286033:
Previous format:    `1.3.3.6 4.2.1.17`
Current format:       `1.3.3.64.2.1.17`
Suggested format: `1.3.3.6;4.2.1.17`

**Comment by JonathanRob** [comment]
Thank you for the feedback, @Hao-Chalmers.

> The detachment of TCDB codes from Yaml and addition to JSON look good. But it is impossible to properly track and check of this modificaiton, until the script is provided

I have now added the curation script `curateModelECcodes` to the `code/modelCuration/` subdirectory.

> A bunch of EC codes were edited by removing "spontaneous", which however are not recorded and will be difficult to follow up. A log file containing the rxn ids of these entries would be convinient for revisiting these cases in the future

Good point. Instead of exporting them to a log file, however, I have added this information as a new `spontaneous` field in the `humanGEMRxnAssoc.JSON` annotation file. The field is numeric, where `0` indicates enzymatic reactions, and `1` indicates a spontaneous reaction.

> Among the reformatted of EC codes, three entires with identical value were found problematic in lines: 285871, 285952, 286033.

You're right, my search criteria was not specific enough to catch these. After updating, I have found and fixed the errors you pointed out, as well as a few others.

**Pull request merged**
