### PR TITLE
removed chebi:71980 from MAM00535, see issue #273

### PR DESCRIPTION
**Pull request by ANiknejad**
I have removed chebi:71980 in the list of xref for MAM00535 in the file metabolite.tsv as discussed in issue #273

### CODE REVIEW

**Comment by ANiknejad** [comment]
I am sorry, I did the pull request on the main instead of the develop, I will try to correct (but I am not so familiar)

**Comment by Hao-Chalmers** [comment]
no worries at all, would it be a good idea to remove/update all these reported ChEBI ids together?

**Comment by mihai-sysbio** [comment]
It should be possible to `Edit` a pull request from the upper-right corner, and then change the target branch. I'll re-open this issue to give it a go.

**Comment by mihai-sysbio** [comment]
Interesting. It looks like the change was done on `ANiknejad:main`. I think the aim is to merge commits to `SysBioChalmers:develop` from `ANiknejad:develop`.

**Pull request closed without merging**
