### PR TITLE
Feat/new annot format issue203

### PR DESCRIPTION
**Pull request by JonathanRob**
### Main improvements in this PR:
Addresses issue #203 by re-formatting the reaction, metabolite, and gene annotation `.json` files in the `data/annotations/` subdirectory as `.tsv` files. The files names were also simplified a bit:

| Before | After |
| ------ | ------|
| humanGEMRxnAssoc.JSON | reactions.tsv |
| humanGEMMetAssoc.JSON | metabolites.tsv |
| humanGEMGeneAssoc.JSON | genes.tsv |

A few advantages to note:
- More human-readable format
- Changes to the same reaction, metabolite, or gene are now on the same line
- File sizes are reduced by ~30%

Since MATLAB's delimited file I/O functions are, in my opinion, a garbage fire, I needed to develop some functions to simplify the import and export of these (and other) `.tsv` files: `importTsvFile` and `exportTsvFile`, respectively.

Finally, annotation data that is expected to be text/strings is enclosed in double quotes ("") in the `.tsv` files, whereas numeric data does not use quotes. Not only was this necessary to automate the `tsv` I/O process, but I figured it was also safer to explicitly define the datatype of each column, so there is no guessing involved.

#### Contributor guidelines
The contributor guidelines were updated to better reflect our current workflow.

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- [X] Selected `devel` as a target branch

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
Random idea: would it make sense to store these under the `model/` folder instead of `data/annotations/` ? I'm thinking they would be more obvious to external people looking into fetching the model.

**Comment by JonathanRob** [comment]
@mihai-sysbio That might actually be a good idea, I was also thinking that these annotations are somewhat "buried" in the repository.

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio sounds good, but how could we get opinions from external users?

**Comment by mihai-sysbio** [comment]
@Hao-Chalmers I've asked for feedback on [Gitter](https://gitter.im/SysBioChalmers/Human-GEM#), so we can give it a few days.

**Comment by Hao-Chalmers** [comment]
very good

**Review by Hao-Chalmers — APPROVED** [review]
This branch nicely addressed the issue #203 - converting annotation file format: `json` -> `tsv`.

In addition, it also attempted to solve the bug reported in #189, plus update **Contributor guidelines** to reflect the latest repo status.

Since the branch already included too many commits/changes, I think it's good to go now.

**Comment by JonathanRob** [comment]
Thanks, @Hao-Chalmers. We can implement the change of annotation file location (in `model/` instead of `data/annotations/`) suggested by @mihai-sysbio in a separate PR.

**Pull request merged**
