### PR TITLE
Merge Pairs Of Irreversible Transport Reactions

### PR DESCRIPTION
**Pull request by Devlin-Moyer**
#### Main improvements in this PR:
For each pair of reactions mentioned in #562:
* Makes the reaction with the lower/smaller ID number reversible
* Copies any E.C. codes and references from the reaction with the lower/smaller ID number to the reaction with the higher/larger ID number
* Removes the reaction with the higher/larger ID number

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by feiranl** [comment]
Nice! but it would be great if you can also merge the cross reference annotations and rxnNotes in the model yaml file and `reactions.tsv` file for the further usage. I am working on the tissue specific tasks. Since recently we removed many rxns, it is difficult to find the `kept rxn` from the old documented rxn ID of the duplicate pair without manually search in the issue.

**Comment by Devlin-Moyer** [comment]
I will start working on that

**Comment by Devlin-Moyer** [comment]
FYI none of the removed reactions had any rxnNotes, but several had EC codes that the kept reactions didn't have, so I copied over both the references and the EC codes

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer good work

just a little concern about the merging: what if it turns out that some import and export reactions of the same metabolites are later associated with different transporters?

**Comment by Devlin-Moyer** [comment]
At the moment, we have no particular reason to believe that's the case (as far as I know -- correct me if I'm wrong), and the presence of these paired irreversible opposite reactions creates a bunch of loops of unbounded fluxes in the model, so it seems reasonable to merge them all now and only separate them back out again when we have a specific reason to intentionally introduce a loop into the model

**Comment by haowang-bioinfo** [comment]
> the presence of these paired irreversible opposite reactions creates a bunch of loops of unbounded fluxes in the model

could you please list these cases

**Comment by Devlin-Moyer** [comment]
Every single pair of reactions in #562 forms a loop that can sustain arbitrarily large flux, since, in each pair of reactions, one has exactly the opposite stoichiometry as the other. I first came across these reactions by getting representative samples of solutions to Human-GEM-derived models and looking for reactions that had average possible fluxes that were suspiciously large (>100 times larger than any bound I had set on an exchange reaction)

**Comment by Devlin-Moyer** [comment]
Since there are only two reactions involved in each, they're very self-contained, but I've been spending a lot of time sampling from solution spaces of models, and each reaction with an unbounded flux is a dimension of the solution space that extends infinitely without ever hitting a bound, which makes the whole process slightly more annoying than it needs to be

**Comment by haowang-bioinfo** [comment]
>> what if it turns out that some import and export reactions of the same metabolites are later associated with different transporters?
>
> At the moment, we have no particular reason to believe that's the case

ture, there is no evidence

> Every single pair of reactions in #562 forms a loop that can sustain arbitrarily large flux, since, in each pair of reactions, both have identical metabolites, and one has exactly the opposite stoichiometry as the other.

yes indeed

> each reaction with an unbounded flux is a dimension of the solution space that extends infinitely without ever hitting a bound, which makes the whole process slightly more annoying than it needs to be

make sense to me

**Comment by feiranl** [comment]
I am ok with the change. As for the unbounded flux, it may be solved by using pFBA @Devlin-Moyer

**Review by haowang-bioinfo — APPROVED** [review]

**Review by haowang-bioinfo — APPROVED** [review]

**Comment by haowang-bioinfo** [comment]
look good!

**Pull request merged**
