### PR TITLE
fix-add a error report in the import/export cycle

### PR DESCRIPTION
**Pull request by feiranl**
## Main improvements in this PR:
This PR is to fix only the bug found in Yaml file, as reported in #628. In the meantime, another PR #635 is to fix error of GH workflow test

### CODE REVIEW

**Comment by feiranl** [comment]
@haowang-bioinfo Could you help to fix this? I add an error catch, but the task still succeed.

**Comment by haowang-bioinfo** [comment]
> I propose a error message to fix the bug.

the issue presumably is due to using previously cached model by the GitHub action cloud server, and a probable solution is to "force" GH action to use freshly loaded model every time. What do you think @mihai-sysbio?

**Comment by mihai-sysbio** [comment]
I'm confused - the test is now successful. Is that right?

My idea was to start by fixing the test first, so that we can confirm that the test will trigger a failure of the GH workflow. Only after that the yaml problem would be fixed, and the re-run of the workflow would then pass.

**Comment by mihai-sysbio** [comment]
I renamed the branch to `fix/importExportCycle`, which then triggered a closure of the PR and deletion of the branch.

**Comment by feiranl** [comment]
It is not ready for closing. There is another bug I identified in importYML. 

the import and export cycle changes the yml file.
MicrosoftTeams-image

**Comment by mihai-sysbio** [comment]
> It is not ready for closing

Absolutely! It was not the intention to close the PR, sorry about that. Normally branch renaming is seamless, but apparently when a PR is already open, GitHub will close it. Let's continue in #635.

**Comment by haowang-bioinfo** [comment]
> There is another bug I identified in importYaml.
the import and export cycle changes the yml file.

yes indeed, working on this now

**Comment by haowang-bioinfo** [comment]
>> There is another bug I identified in importYaml.
the import and export cycle changes the yml file.
>
> yes indeed, working on this now

this bug is located from Yaml file line 307295: `- metabolties: !!omap`, where there is typo that supposed to be `metabolites`. This particular bug was introduced in #606

**Comment by haowang-bioinfo** [comment]
this PR is reopened for fixing yaml import/export cycle only, while the issue of GH workflow test will be fixed in #635

**Comment by feiranl** [comment]
LGTM! The import and export cycle works fine now

**Review by haowang-bioinfo — APPROVED** [review]

**Pull request merged**
