### PR TITLE
Remove Two-Step Carbonic Anhydrase Reactions & Carbonate Metabolites

### PR DESCRIPTION
**Pull request by Devlin-Moyer**
#### Main improvements in this PR:
Implements changes proposed in #589:
- Removes `MAR05406` and `MAR08749` for being redundant with `MAR03955`
- Removes `MAR08751` and `MAR08750` for being redundant with `MAR03956`
- Makes `MAR03955` and `MAR03956` reversible
- Removes `MAR05409` (one of the two extracellular reactions)
- Edits `MAR05407` to `MAM01596e + MAM02040e <-> MAM02039e + MAM02046e` so that all compartments accomplish the carbonic anhydrase reaction in only a single step
- Removes `MAR13066` (carbonate exchange reaction)
- Removes `MAM01421e`, `MAM01421c`, and `MAM01421m` (carbonate)

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by Devlin-Moyer** [comment]
I'm not sure how it happened, but there was a merge conflict with deprecatedReactions.tsv: there were two extra rows that weren't on my fork, so I just resolved the merge conflict on the GitHub website, which is what that last commit is and why it's not helpfully named

**Comment by haowang-bioinfo** [comment]
No worries, will take care of it

**Review by haowang-bioinfo — APPROVED** [review]
everything looks fine

**Review by feiranl — APPROVED** [review]
LGTM!

**Pull request merged**
