### PR TITLE
feat: more annotation for genes

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:
Metabolic Atlas had enhanced the annotation of genes outside the Human-GEM. With this PR, the aim is to migrate the annotation closer to the model. This can also be seen as a contribution to #224. Once this is merged, the original file `GENES.tsv` from the repository [MetabolicAtlas/data-files](https://github.com/MetabolicAtlas/data-files) may be removed.

**I hereby confirm that I have:**

- [ ] Tested my code on my own computer for running the model
- [x] Selected `develop` as a target branch

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
@Hao-Chalmers the updated `genes.tsv` file ends with some genes that are no longer present in the latest version of Human-GEM. I'm thinking these should be removed - but maybe it is worth double checking these manually?

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio what do you mean by "some genes that are no longer present in the latest version of Human-GEM"?

**Comment by mihai-sysbio** [comment]
The annotation enrichment was performed on an earlier version of Human-GEM, so my guess is that there are a few genes which have been removed/curated, perhaps due to the removal of certain reactions or GPR curation. @pecholleyc might know more about this.

**Comment by Hao-Chalmers** [comment]
A relevant [issue](https://github.com/SysBioChalmers/Human-GEM/issues/157) is open for this.

**Comment by pecholleyc** [comment]
Yes, the additional annotations (the alternate name and the synonyms, other columns are emty) were generated in 2019, and were extracted from the Ensembl database. I think the [get_ensembl_ID_mapping.py](https://github.com/SysBioChalmers/Human-GEM/blob/master/code/modelCuration/GPRs/get_ensembl_ID_mapping.py) could be used to generate the [genes.tsv](https://github.com/SysBioChalmers/Human-GEM/blob/master/model/genes.tsv) file, depending on what new annotations you want to include in that repo. I would suggest to close the PR and continue the discussion the relevant issue.

**Comment by mihai-sysbio** [comment]
This PR is addressing the shortcoming of the missing annotation from Human-GEM that is showcased on Met Atlas at the moment.
I am in full support, in addition to this PR, to create an issue to discuss ways to improve this fetching this annotation.

**Comment by mihai-sysbio** [comment]
@Hao-Chalmers with the removal of the "old" genes in 6a17e79, the `yaml-validation` has now passed.

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio can you please specify the additional annotations required by Metabolic Atlas under #157.

**Comment by mihai-sysbio** [comment]
@Hao-Chalmers I already did [here](https://github.com/SysBioChalmers/Human-GEM/issues/157#issuecomment-814002339). All the new columns added in the PR are used on Metabolic Atlas, except for the last two which are empty at the moment. Somehow I have the memory we showing the EC code on the Gene page.

**Review by JonathanRob — APPROVED** [review]

**Review by Hao-Chalmers — APPROVED** [review]

**Pull request merged**
