### PR TITLE
fix: unmappable references

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:
This PR aims to completely resolve the issues in the `references` field #259, such that this field contains a list of `PMID:\d+` separated bty `;`. Since this affects only the `references` field, no testing will be done on the model.

**I hereby confirm that I have:**

- [ ] Tested my code on my own computer for running the model
- [x] Selected `develop` as a target branch

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
At the moment the "bad" fields were reduced from 196 to
>❯ grep -inr "??" Human-GEM.yml | wc -l      
      93

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio such a nice job

**Comment by mihai-sysbio** [comment]
I propose leave it as a draft PR. Maybe somebody will have time to finish fixing the remaining broken references, at which point it can be made `Ready for review`.

**Comment by mihai-sysbio** [comment]
```
❯ grep -c "??" Human-GEM.yml         
70
```

**Comment by mihai-sysbio** [comment]
It looks like this PR will be ready for review after the next round:
```
❯ grep -c "??" Human-GEM.yml                                  
27
```

**Review by haowang-bioinfo — APPROVED** [review]

**Comment by haowang-bioinfo** [comment]
might be good to wrap up the merged PRs into a new release? @mihai-sysbio @JonathanRob

**Comment by JonathanRob** [comment]
Yes, I was thinking the same.

**Comment by haowang-bioinfo** [comment]
@JonathanRob will draft one for your review

**Pull request merged**
