### PR TITLE
Human 1.12

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:

- Features (PR #393):
	- speed up `importYaml` in loading model fields
- Features (PR #392):
	- turn `importYaml` into a more generic function
- Features (PR #388):
	- add help functions that are used together with ftINIT in RAVEN
- Fixes (PR #382):
	- change metabolic task file format from `xlsx` to `txt`
	- inactivate human biomass reaction (MAR13082), as suggested in Mouse-GEM PR #11
	- add proper LB and UB values to annotation field, as reported in Mouse-GEM PR #12
	- turn annotateGEM into a more generic function, as discussed in Convert `annotateGEM` into a more generic function #380
- Fixes (PR #379):
	- flag reactions MAR05127, MAR08749, MAR08750 as spontaneous, as identified in #349
- Style (PR #374):
	- doc: tINIT rename 'exchange metabolites' to 'boundary metabolites in `getINITModel2`
- Features (PR #367):
	- add reaction names from KEGG, to address #181
- Fixes (PR #365):
	- merge MAR08973 into MAR04474, as suggested in #346
- Fixes (PR #362):
	- resolves #342 by applying the suggestion to remove the gene (and thus the GPR) and mark `MAR04840` as spontaneous
- Fixes (PR #358):
	- correct CHEBI associations to avoid conflict during MNXref conversion

### CODE REVIEW

**Review by haowang-bioinfo — APPROVED** [review]
lgtm, reformatted the PR messages a bit

**Review by JonathanRob — APPROVED** [review]
I assume the merge conflict has something to do with the date in the Human-GEM.yml file, maybe?

**Comment by haowang-bioinfo** [comment]
> I assume the merge conflict has something to do with the date in the Human-GEM.yml file, maybe?

The merge from `develop` into `main` is detailed in the [wiki](https://github.com/SysBioChalmers/Human-GEM/wiki/How-to-make-a-new-release)

**Comment by JonathanRob** [comment]
Ok, thanks, @haowang-bioinfo. It's weird, I was trying to view the new release instructions on the wiki recently and it wasn't loading properly, but now it seems to work.

**Comment by haowang-bioinfo** [comment]
will just merge this and move things forward

**Pull request merged**
