### PR TITLE
Remove lipid droplet breakdown reaction MAR00032

### PR DESCRIPTION
**Pull request by Devlin-Moyer**
#### Main improvements in this PR:
Removes `MAR00032` and associated non-metabolic genes  `ENSG00000072062`, `ENSG00000142875`, `ENSG00000165059`, `ENSG00000172531`, `ENSG00000186298`, and `ENSG00000213639`, as proposed in #631

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by Devlin-Moyer** [comment]
Apparently `MAR00032` was the only reaction that `ENSG00000072062`, `ENSG00000142875`, `ENSG00000165059`, `ENSG00000172531`, `ENSG00000186298`, and `ENSG00000213639` were associated with (that's why the YAML validation failed); @JonathanRob, since you mentioned that some of the gene associations with `MAR00030` were questionable, have you maybe already determined that any/all of these genes should be removed from Human-GEM entirely?

**Comment by JonathanRob** [comment]
Yes, it's fine to remove these genes from the model altogether.

**Comment by haowang-bioinfo** [comment]
> Yes, it's fine to remove these genes from the model altogether.

these 6 genes encode either kinases or phosphatases that undertake regulatory activies.

**Review by haowang-bioinfo — APPROVED** [review]
the questionable GPR of MAR00032 supports its removal

**Pull request merged**
