### PR TITLE
Fix FAD/Ubiquinone Duplicates

### PR DESCRIPTION
**Pull request by Devlin-Moyer**
#### Main improvements in this PR:

As discussed in #607:
- Removes `MAR02035` for being a duplicate of `MAR03121`
- Removes `MAR03211` for being a duplicate of `MAR03212`
- Removes `MAR03751` for being a duplicate of `MAR03752`
- Removes `MAR03783` for being a duplicate of `MAR03784`
- Removes `MAR04242` for being a duplicate of `MAR04243`
- Removes `MAR03769` for being a duplicate of `MAR03770`
- Removes `MAR03838` for being a duplicate of `MAR08611`
- Removes `MAR02366` for being a duplicate of `MAR03136`
- Removes `MAR02367` for being a duplicate of `MAR03135`
- Removes `MAR02370` for being a duplicate of `MAR03128`
- Removes `MAR02372` for being a duplicate of `MAR03156`
- Removes `MAR02369` for being a duplicate of `MAR03149`
- Removes `MAR02373` for being a duplicate of `MAR03142`
- Removes `MAR00483` for being a duplicate of `MAR00482`/`MAR00449`/`MAR01169`
- Removes `MAR08743` for being a duplicate of `MAR04652`

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by Devlin-Moyer** [comment]
I have no idea how to interpret the error message generated by the YAML validation check

**Comment by feiranl** [comment]
I am a little bit afraid of this kind of changes. In case reviewers merge this PR, I tag this PR for draft first. Discussions will come later in the Issue page.

**Comment by Devlin-Moyer** [comment]
nope I still don't know why the YAML validation test is failing

**Comment by mihai-sysbio** [comment]
I'll have a look, perhaps I can spot something

**Comment by mihai-sysbio** [comment]
First thing I'm trying is to run the validation locally on this PR with
```
python code/test/sanityCheck.py
```
This returns the same error
> Traceback (most recent call last):
  File "/Users/petre/Human-GEM/code/test/sanityCheck.py", line 105, in <module>
    checkUnusedEntities(model, "genes")
  File "/Users/petre/Human-GEM/code/test/sanityCheck.py", line 96, in checkUnusedEntities
    assert len(unused_entities) == 0, f"Found unused {{entity_type}}!"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Found unused {entity_type}!

It seems the other PRs are passing this test, so a more in-depth look is required. Sorry I cannot do more at the moment, but I'll try to get back to this tomorrow.

**Comment by Devlin-Moyer** [comment]
Aha the problem is that `MAR03769` was the only reaction that `ENSG00000128928` (IVD) was associated with; it clearly should have also been associated with `MAR03770`, since [IVD is an FAD-dependent enzyme](https://www.uniprot.org/uniprotkb/P26440/entry), but removing `MAR03769` made IVD into an "unused gene"
I'm gonna add `ENSG00000128928` to the GPR of `MAR03770` unless anyone has any objections to (hopefully) get this to pass the YAML validation test

**Comment by Devlin-Moyer** [comment]
since @feiranl requested it in #625 and seemed uneasy about this PR, I figured I'd also go through and merge the reaction annotations from the deleted reactions into the kept ones

**Comment by mihai-sysbio** [comment]
@Devlin-Moyer I'm glad you figured out the unused gene.
I've pushed a commit on this branch that improves the validation output as [suggested above](https://github.com/SysBioChalmers/Human-GEM/pull/613#issuecomment-1579698003). If you feel this is not the right place, please feel free to remove it from this PR.

**Comment by haowang-bioinfo** [comment]
@Devlin-Moyer please merge latest develop this branch

**Review by haowang-bioinfo — APPROVED** [review]

**Pull request merged**
