### PR TITLE
Add new reactions annotated for genes related to Glycolysis pathway

### PR DESCRIPTION
**Pull request by feiranl**
#### Main improvements in this PR:
* Add 87 new mets, 68 new reactions for genes related to Glycolysis pathway according to the #507 

* Fix one naming issuse identified in the process #519 :
remove the metabolite [MAM00077x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00077x), as it only relate to 2 rxns, while the duplicate [MAM02766x](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02766x) is associated with 13 rxns from all compartments 
remove reaction  [MAR03489](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03489) and merge the GPR to its duplicate rxn [MAR03387](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03387) as discussed 
remove reaction [MAR03488](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03488) as discussed

**I hereby confirm that I have:**

- [ ] Tested my code on my own computer for running the model
- [ ] Selected `develop` as a target branch
- [ ] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by haowang-bioinfo** [comment]
The `Yaml validation` step verifies the consistency between Yaml model file and tsv files of `reactions.tsv` and `metabolites.tsv`. The failure of this step means that tsv files should be modified to match with the model, which, as demonstrated by the `Yaml conversion` step,  appears to be fine.

**Comment by mihai-sysbio** [comment]
Looking into the logs of the validation check below, it seems many (all?) errors are caused: ```trailing spaces  (trailing-spaces)```. This means that in `Human-GEM.yml` spaces have been added at the end of the line.

**Comment by mihai-sysbio** [comment]
After correcting the trailing spaces in commit `037e7b8`, the error that @haowang-bioinfo indicated previous becomes obvious in the logs as well:
```
  File "/__w/Human-GEM/Human-GEM/code/test/sanityCheck.py", line 53, in checkMetAnnotation
    assert metList == mets, "Metabolite annotation mismatch!"
AssertionError: Metabolite annotation mismatch!
Error: Process completed with exit code 1.
```

**Comment by feiranl** [comment]
@mihai-sysbio could you tell me what should I do to fix this error? I thought it was that I reused the deprecated met IDs, but I   intersected the mets in `metabolites.tsv` and `deprecatedMetabolites.tsv` and found none.

**Comment by mihai-sysbio** [comment]
> @mihai-sysbio could you tell me what should I do to fix this error? I thought it was that I reused the deprecated met IDs, but I   intersected the mets in `metabolites.tsv` and `deprecatedMetabolites.tsv` and found none.

My suspicion is that some of the new identifiers added in the YML file have not been added to the TSV. One can run the Python code locally as well (with a printout) to see the exact problem. Let me know if you can't find the root cause.

**Comment by feiranl** [comment]
Closing this PR since it was redo in #534 and #535. This error in yaml validation was caused by the inconsistent met order in model.mets and metAnnotation file.

**Pull request closed without merging**
