### PR TITLE
feat: curate subsystems, resolves issue #205

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:
The aim is to address issue #205.

**I hereby confirm that I have:**

- [x] Tested my code on my own computer for running the model
- [x] Selected `devel` as a target branch

### CODE REVIEW

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio nice work.

Please make sure the updated `yml` model file could pass the test using function `testYamlConversion`.

**Comment by mihai-sysbio** [comment]
Is there a guide on how to run this function `testYamlConversion`?

**Comment by Hao-Chalmers** [comment]
No, this test function has not been included in the [Contribution guidelines](https://github.com/SysBioChalmers/Human-GEM/blob/master/.github/CONTRIBUTING.md). But thanks for your reminding, we'll update the guidelines by incorporating the this other changes about the yml-based workflow soon.

**Comment by mihai-sysbio** [comment]
Alright, it must be fine since all the output was `ans = 1 `. Just a heads-up, all I needed for the test was RAVEN (no COBRA, no libSBML, no Gurobi).

**Comment by Hao-Chalmers** [comment]
@mihai-sysbio very good.

**Review by Hao-Chalmers — APPROVED** [review]

**Pull request merged**
