### PR TITLE
fix: remove or merge near-duplicate reactions

### PR DESCRIPTION
**Pull request by Devlin-Moyer**
#### Main improvements in this PR:
Removes the following reactions, as discussed in #561:
- MAR04562
- MAR00464
- MAR11310
- MAR10410
- MAR02490
- MAR08985
- MAR08992
- MAR20045
- MAR20004

Also adds "or ENSG00000198099" to the GPR of MAR06644 (the reaction that MAR20004 was a duplicate of)

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by haowang-bioinfo** [comment]
have a say that the commit 73b165859873259ed81f5fff08db69447fe96604 is confusing because it appears to be irrelevant to the PR message @Devlin-Moyer

**Comment by Devlin-Moyer** [comment]
Huh that is bizarre; I definitely remember removing those reactions, and am not sure where all those changes came from? I think some weird Git thing happened where I accidentally got this entangled with the PR about reversing PPI reactions somehow; I'll fix this when I get to my work laptop in ~1-2 hours

**Comment by Devlin-Moyer** [comment]
okay I don't know what's going on so I'm just scrapping this and starting over

**Comment by haowang-bioinfo** [comment]
> okay I don't know what's going on so I'm just scrapping this and starting over

that's fine and no worries

**Pull request closed without merging**
