### PR TITLE
Remove PPARA Reactions

### PR DESCRIPTION
**Pull request by Devlin-Moyer**
#### Main improvements in this PR:
As discussed in the comments on #580, removes all reactions involving `MAM01268` or `MAM02757` in all compartments:
- `MAR00024`
- `MAR00025`
- `MAR00026`
- `MAR00027`
- `MAR00028`
- `MAR00029`
- `MAR05173`
- `MAR05289`
- `MAR13064`

Also removes all metabolites that only participated in those reactions:
- `MAM01816n`
- `MAM01268c`
- `MAM01268e`
- `MAM01268m`
- `MAM01268n`
- `MAM01268r`
- `MAM01268x`
- `MAM02757c`
- `MAM02757l`
- `MAM02757n`

Also removes all genes that only participated in one or more of these reactions:
- `ENSG00000069667`
- `ENSG00000101849`
- `ENSG00000118137`
- `ENSG00000126368`
- `ENSG00000135744`
- `ENSG00000137574`
- `ENSG00000139278`
- `ENSG00000140396`
- `ENSG00000141027`
- `ENSG00000142453`
- `ENSG00000143344`
- `ENSG00000158874`
- `ENSG00000166821`
- `ENSG00000167772`
- `ENSG00000169375`
- `ENSG00000170485`
- `ENSG00000171720`
- `ENSG00000177565`
- `ENSG00000186350`
- `ENSG00000186951`
- `ENSG00000196498`
- `ENSG00000198646`

**I hereby confirm that I have:**
- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
- [X] Any removed reactions and metabolites have been moved to the corresponding deprecated identifier lists

### CODE REVIEW

**Comment by Devlin-Moyer** [comment]
Apparently `MAR00024` was the only reaction that `MAM01816n` participated in, so I'm also going to remove that

**Comment by haowang-bioinfo** [comment]
this is a natural follow-up implementation to the discussion in #580 - nice work @Devlin-Moyer 

if to remove all reactions involving MAM01268, should [MAR00030](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR00030) be also be removed?

**Comment by Devlin-Moyer** [comment]
`MAR00030` was removed by #657

**Review by haowang-bioinfo — APPROVED** [review]
these removed genes are mostly annotated with regulatory function. In particular, [ENSG00000137574](https://www.uniprot.org/uniprotkb/Q96RS0/entry) and [ENSG00000142453](https://www.uniprot.org/uniprotkb/Q86X55/entry) are assigned with methyltransferase activity. Still they don't appear to be involved into any metabolic process.

it's okay to remove the genes in my view, and they can be added later once concrete evidence is provided

**Pull request merged**
